const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const k=[];

k.push(...cover("Therapeutic Interventions II (DPTH 6241)","Module 7: Pulling It All Together — Exercise Guidelines and PNF",
 "Topic 7.1: General Exercise Guidelines by Body Region (spine, shoulder, elbow/forearm, wrist/hand, hip, knee, ankle/foot) — Dr. Shaw • Topic 7.2: Proprioceptive Neuromuscular Facilitation — Dr. Mierau",
 ["Watch the lectures in your own Canvas module — these notes condense them, they don't replace them",
  "★ The FIVE AREAS you address in every body region: kinesthetic awareness · mobility and flexibility · muscle performance and motor control · cardiopulmonary endurance · functional activities. Only the EMPHASIS changes by stage",
  "Text: Kisner & Colby chapters 15–22 · lab immersion March 30 – April 1, practical on day 3"]));

/* ─────────────── 7.1 FRAMEWORK ─────────────── */
k.push(banner("TOPIC 7.1","General Exercise Guidelines — the Universal Framework"));
k.push(spacer());
k.push(infoBox("The one slide behind all seven regional lectures",["**Five areas, every body region, every time**: (1) **kinesthetic awareness** · (2) **mobility and flexibility** · (3) **muscle performance and motor control** · (4) **cardiopulmonary endurance** · (5) **functional activities**. The region doesn't change the list — **the stage of healing and phase of rehabilitation change the EMPHASIS**. Notice, for example, that cardiopulmonary endurance barely features in the acute/protection phase and arrives in the controlled-motion phase."],C.green,C.lightGreen));
k.push(bullet("**The three rehab phases** map onto the healing stages you already know: **protection (acute)** → **controlled motion (subacute)** → **return to function (chronic)**. Kisner & Colby **table 16.1** crosses the five areas against those phases; that grid is the single most useful study tool in this topic."));
k.push(h1("The Spine (7.1)"));
k.push(detail(["Pathology","Diagnostic bias + intervention focus"],[
 ["**Degenerative joint disease / OA**","**FLEXION bias** — flexing the spine relieves"],
 ["**Herniated disc**","**EXTENSION bias** — herniation is usually posterolateral, so extension helps move disc material back. **Protrusion** = displaced material continuous with the disc, base wider than what extends into the canal (nuclear material still contained by the outer annulus and ligaments); **extrusion** is beyond that"],
 ["**Compression fracture (osteoporosis)**","**EXTENSION bias**"],
 ["**Postural pain syndrome**","No diagnostic category — postural strain or poor physical condition"],
 ["**Tension headache**","**FLEXION bias with lower cervical extension**"]],[2600,6760]));
k.push(bullet("**Disc protrusion impairments** (Kisner box 15.1): pain and muscle guarding · flexed posture with deviation to the symptomatic side · neurological symptoms in dermatomes and myotomes · **peripheralization with sitting, prolonged flexed postures, sit-to-stand transitions, coughing, and straining** · limited nerve mobility. **Interventions**: ambulation and resumption of activity · pain control · education on healthy lifestyle and weight · **stretching (evidence equivocal — probably won't hurt, may not help)** · strengthening and core stability · **grade 1–2 oscillations** for short-term acute pain relief · **TENS** for pain and mobility · **traction** (positive effects on pain, disability, and SLR in herniation; mechanical traction added to medication and e-stim was the most effective combination in one trial) · **aquatic vertical traction** (better centralization and greater pain reduction than land traction, especially with nerve root symptoms) · heat for blood flow · **cryotherapy in the acute phase** · ultrasound for connective tissue extensibility."));
k.push(bullet("**Facet joint pathology** (box 15.2): pain, impaired mobility and posture, impaired spinal extension; flexibility demands and prolonged repetitive trunk motion (lifting, carrying) aggravate. Focus: **patient education including pain education to counter catastrophizing** · **relative rest — bed rest beyond two days is NOT recommended** (undesirable effects on bone, connective tissue, muscle, and cardiovascular system; complete inactivity makes back pain worse) · **reduce lumbar lordosis** with pelvic tilts in multiple positions, since excess lordosis loads the posterior elements and facets · pain relief from trunk exercise **combined** with mobilization and medication/NSAIDs (the combination beats any single element)."));
k.push(bullet("**Spinal stabilization progression** (boxes 16.1–16.2): **kinesthetic training** first — head nods and pelvic tilts, awareness of **neutral spine**, awareness of what ADLs do to spinal motion and what relieves versus provokes. Then **stabilization training** — activate the **deep segmental muscles** (cervical: head nods/cranio-cervical flexion; lumbar: the drawing-in maneuver), elicit **superficial global control** (erector spinae), and coordinate segmental activation with a stable neutral spine and pelvis. Then **functional training** — body mechanics layered on a stable spine: rolling, bed mobility, sit-to-stand, walking. **Progressive limb loading** (table 16.2–16.3) escalates by phase: max protection = shoulder flexion and abduction **to 90°**, ER at the side → moderate protection = **end-range** flexion and abduction → minimal/no protection = **diagonal patterns — which is exactly where PNF enters**."));
k.push(h1("The Extremities (7.2–7.7) — the Repeating Pattern"));
k.push(detail(["Region","What's specific to it"],[
 ["**Shoulder (17)**","**Scapulohumeral rhythm** preserves the length-tension relationship of the glenohumeral muscles and sustains force production through range. Scapular motion = **3 motions** (upward/downward rotation, internal/external rotation, anterior/posterior tilt) **+ 2 translations** (up/down on the thorax, medial/lateral around its curvature). **Muscles prone to TIGHTNESS**: upper trapezius, levator scapulae, pec major and minor, upper cervical extensors, SCM, scalenes, teres major/minor, subscapularis. **Prone to LENGTHENING**: middle and lower trapezius, rhomboids, serratus anterior, deep neck flexors, supraspinatus, infraspinatus. **Winging** specifically implies serratus anterior weakness or paralysis; **dyskinesia** is broader"],
 ["**Elbow / forearm (18)**","Nerve first: **ulnar** compressed at the cubital tunnel and between the two heads of FCU · **radial** at the proximal forearm near supinator · **median** between the heads of pronator teres. Pain by location: **anterior** (capsular strain, distal biceps rupture or tendinitis, dislocation, pronator syndrome) · **medial** (medial epicondylitis, UCL injury, flexor-pronator strain, fracture, little league elbow, valgus extension overload) · **posteromedial** (olecranon tip stress fracture, posterior impingement in throwers, trochlear chondromalacia) · **posterior** (olecranon bursitis, olecranon stress fracture, triceps tendinitis) · **lateral** (capitellum fracture, cervical radiculopathy or referred pain, lateral epicondylitis, LCL injury, osteochondral changes, osteochondritis dissecans)"],
 ["**Wrist / hand (19)**","Deformities worth recognizing: **swan neck** — PIP laxity with overstretched volar plate and bowstringing of the lateral bands → **PIP hyperextension with DIP flexion** (advanced RA) · **boutonnière** — rupture of the central slip, lateral bands migrate volarly → **PIP flexion with DIP extension** · **zigzag thumb deformity** from muscle imbalance and ligamentous laxity, with adductor pollicis tightness contributing. Acute phase: protect the joints, activity modification, pain management, **grade 1–2 distraction and oscillation**, orthoses (**night hand-positioning orthoses improve pain, grip, pinch, and function**; ring/thermoplastic orthoses correct swan neck; soft neoprene supports address ulnar drift). Later: **grade 3 sustained or grade 4 mobilizations**, mobilization with movement at wrist, MP and IP joints"],
 ["**Hip (20)**","Hypomobility impairments: pain, stiffness at rest, limited motion with a **firm end feel**, asymmetry, limited hip AND knee extension, impaired balance and postural control. Acute-phase tactics with a nice practical flavor: **grade 1–2 oscillations in the resting position**, a **rocking chair** for gentle oscillation and mechanoreceptor stimulation, an assistive device to unload the joint — **cane or crutch in the hand OPPOSITE the painful hip** — a **shoe lift** for leg-length asymmetry, elevated firm chairs and commodes"],
 ["**Knee (21)**","**OA affects the MEDIAL compartment more than the lateral.** Post-traumatic: swelling that is **immediate = bleeding (hemarthrosis)** vs **>4 hours = serous effusion**. **Effusion is most comfortable near 25° of flexion** — which explains flexion contracture risk. **Reflex inhibition of quadriceps from joint distension**, quad and hip abductor weakness, **extensor (quad) lag**, instability, impaired balance. Acute: control pain, protect, PROM/AAROM/AROM within pain limits (gravity-minimized sidelying if needed), **quad sets and hamstring sets to prevent patellar adhesions**, straight leg raises, submaximal closed-chain setting, grade 1–2 distraction and AP glides → grade 3–4 later"],
 ["**Ankle / foot (22)**","Hypomobility from RA, DJD, trauma, post-immobilization stiffness, **gout**. Impairments: restricted motion, alignment deformity, weakness, impaired balance and postural control, **increased fall frequency**, painful weight-bearing, gait deviation. Acute: education and joint protection, HEP, **daily ROM and endurance emphasis**, assistive device, modalities, **grade 1–2 distraction and oscillation**, **orthotic or shoe insert** for biomechanics, aquatic therapy, muscle setting. Later: grade 3 sustained or grade 3–4 oscillations, **mobilization with movement at the talocrural joint for plantarflexion and dorsiflexion**, balance and proprioception, cardiopulmonary fitness. Leg/heel/foot pain (tendinosis, tendinitis, tenosynovitis, shin splints) is usually **biomechanical overload**: obesity, prolonged standing at work, faulty LE alignment, muscle imbalance or fatigue, **training errors and improper footwear**"]],[2200,7160]));

/* ─────────────── 7.2 PNF ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 7.2","Proprioceptive Neuromuscular Facilitation"));
k.push(spacer());
k.push(bullet("**What PNF is**: an approach to therapeutic exercise combining **functional diagonal movement patterns** with **neuromuscular facilitation techniques**. Everyday movement runs in diagonals, and within a diagonal **a stronger muscle group can facilitate a weaker one**. PNF improves motor control and function in both neuromuscular and musculoskeletal conditions, and it **spans every stage of healing** — isometrics early, high-speed diagonals against maximal resistance late. You've already used two PNF techniques without the label: **contract-relax and hold-relax**."));
k.push(h1("1. Nomenclature — the thing that trips everyone ★"));
k.push(infoBox("How to name a diagonal",["Each extremity has **two diagonals — D1 and D2 — each performed in flexion or extension**, giving four patterns per limb. **The name comes from what the SHOULDER (or HIP) is doing at the END of the pattern**, not the elbow, wrist, or knee. Finish with the shoulder flexed → it's a flexion diagonal. Finish extended → extension diagonal. Whether it's D1 or D2 is memorization — anchor it with an image."],C.gold,C.lightGold));
k.push(compare("UPPER EXTREMITY imagery","LOWER EXTREMITY imagery",
 ["**D1 = the SEAT BELT** — reaching across the body and pulling down to buckle. **D2 = the SWORD or the DISCO move** — drawing the sword up and out (D2 flexion), sheathing it down and across (D2 extension)."],
 ["**D1 = HACKY SACK** in the flexion position, and **putting out a bike kickstand** for extension. **D2 flexion = the 'doggy' position**; D2 extension brings the foot back and behind so the legs cross."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(h1("2. Basic Procedures — the six things you're doing at once"));
k.push(detail(["Procedure","How to execute it"],[
 ["**Manual contacts**","Hands **over the AGONIST** (the muscle producing the force) so resistance lands on the right group and the touch cues the desired direction. In extremity patterns: **one contact DISTAL — where the movement begins — and one PROXIMAL**. Put a hand in the wrong place and the patient moves the wrong way even when your words are right"],
 ["**Maximal resistance**","**As much as the patient can handle while still moving slowly, under control, and pain-free through the available range** — accommodating and adjusting through the range for differences in strength and pain. Early post-op that may mean no resistance at all: passive or active ROM only"],
 ["**Therapist position and movement**","Align your body **with the direction of the diagonal**, wide base of support, and move and pivot over that base — protects you and lets the rotation happen"],
 ["**Stretch**","Place the muscles about to contract in a **LENGTHENED position** first. A **quick stretch (stretch reflex)** to the distal group can elicit the contraction — but **not appropriate in acute stages**"],
 ["**Normal timing**","Coordinated movement runs **DISTAL to PROXIMAL** — sequence the distal component first, then the proximal, to promote normal neuromuscular control"],
 ["**Verbal and visual cues**","Short, precise auditory cues up front, **faded and removed** as the patient learns the pattern; and **have the patient WATCH the limb move** to enhance control through range"]],[2400,6960]));
k.push(h1("3. PNF Techniques ★"));
k.push(detail(["Technique","What it is and when to use it"],[
 ["**Rhythmic initiation**","Builds the patient's ability to INITIATE the pattern: **passive → active-assisted → active → (then resisted)**. Teach the pattern passively with cues and visual tracking, then hand it over as the stage of healing allows. This is the default teaching method for every diagonal"],
 ["**Repeated contractions**","Dynamic contractions with **quick stretches plus resistance through the range** — used to strengthen a weak agonist at the specific point in the range where it falters"],
 ["**Reversal of antagonists (slow reversal)**","The **stronger agonist pattern immediately followed by the weaker antagonist pattern**, with no rest — rapid reciprocal action mimicking real function (chopping wood, swinging an axe, tennis, dance, grasp-and-release). **Slow reversal HOLD** adds an isometric hold at each end for proximal dynamic stability"],
 ["**Alternating isometrics**","Manual resistance in a **single plane, one side of the segment then the other**, with the patient instructed simply to HOLD — isometric strengthening of agonists and antagonists, open or closed chain. Good in more acute phases and for stabilization"],
 ["**Rhythmic stabilization**","The **progression of alternating isometrics**: usually weight-bearing, **multidirectional resistance applied simultaneously** while the patient holds — multiple muscle groups stabilizing at once, which is what real life demands"]],[2400,6960]));

/* ─────────────── PATTERNS ─────────────── */
k.push(pageBreak());
k.push(banner("PNF PATTERNS","Upper and Lower Extremity Diagonals"));
k.push(spacer());
k.push(detail(["Pattern","Joint positions · hand placement · verbal cues"],[
 ["**UE D1 FLEXION** (the seat belt, buckling)","**Start**: shoulder extension-abduction-internal rotation, elbow extended, forearm pronated, hand **8–12 inches from the hip**. **End**: arm across the face — shoulder flexion-**adduction**-external rotation, elbow flexed, forearm **supinated**, wrist and fingers flexed. **Hands**: 2–3 fingers in the patient's palm + cubital fossa/distal forearm (facilitating the flexors). **Cues**: “Squeeze my fingers, turn your palm up, pull your arm up and across your face”"],
 ["**UE D1 EXTENSION**","**Start** where D1 flexion ended. **End**: shoulder extension-abduction-internal rotation, elbow extended, forearm pronated, wrist and fingers extended, hand 8–12 inches from the hip. **Hands**: dorsal surface of the hand + extensor surface proximal to the elbow (triceps). **Cues**: “Open your hand, push your arm down and out”"],
 ["**UE D2 FLEXION** (drawing the sword / disco)","**Start**: forearm across the umbilicus. **End**: shoulder flexion-**abduction**-external rotation, elbow extended, forearm supinated, wrist and fingers extended, arm **8–10 inches from the ear, thumb pointing toward the floor**. **Hands**: dorsum of the hand with a **lumbrical grip** (webbing between thumb and forefinger) + dorsal forearm near the elbow. **Cues**: “Open your hand and turn it toward your face, lift your arm up and out, point your thumb out”"],
 ["**UE D2 EXTENSION** (sheathing the sword)","**Start** 8–10 inches from the ear. **End**: forearm across the umbilicus — shoulder extension-adduction-internal rotation, forearm pronated, wrist and fingers flexed (elbow mostly extended, sometimes slight flexion). **Hands**: index and middle fingers in the palm + volar forearm or distal humerus. **Cues**: “Squeeze my fingers and pull down and across your chest”"],
 ["**LE D1 FLEXION** (hacky sack)","**Start**: hip extension-abduction-internal rotation, knee extended, ankle plantarflexed and everted, toes flexed. **End**: hip flexion-**adduction across midline**-external rotation, knee flexed, ankle dorsiflexed and inverted, toes extended. **Hands MEDIAL** — medial/dorsal foot and toes + anteromedial thigh just proximal to the knee. **Cues**: “Pull your foot and toes up and in, bend your knee, pull your leg over and across”"],
 ["**LE D1 EXTENSION** (the kickstand)","**Start** where D1 flexion ended. **End**: hip extension-abduction-internal rotation, knee extended, ankle plantarflexed and everted. **Hands**: lateral and plantar surface of the foot and base of the toes + **posterior knee in the popliteal fossa** (supporting throughout and cueing internal rotation at the end). **Cues**: “Point your toes, push down and out”"],
 ["**LE D2 FLEXION** (the doggy position)","**Start**: hip extension-external rotation-adduction, knee extended, ankle plantarflexed and inverted. **End**: hip flexion-**internal rotation-abduction**, knee flexed, ankle dorsiflexed and everted. **Hands LATERAL** — dorsal and lateral foot + anterolateral thigh just proximal to the knee, **fingers pointing distally** for control. **Cues**: “Foot and toes up and out, lift your leg up and out”"],
 ["**LE D2 EXTENSION**","**Start** in the flexed/abducted/IR position. **End**: hip extension-adduction-external rotation, knee extended, ankle plantarflexed and inverted. **Hands**: plantar and medial foot (facilitating plantarflexion plus initial adduction and ER) + posteromedial thigh for support and adduction cueing. **Cues**: “Point your toes down and in, push your leg down and in”"]],[2200,7160]));
k.push(tip("Do NOT memorize the joint-position charts — they're straight out of Kisner & Colby and they'll be in front of you. Memorize the IMAGES (seat belt, sword, hacky sack, doggy), the naming rule (name it for where the shoulder or hip ENDS), and the principle behind hand placement: PUT YOUR HANDS WHERE YOU WANT THE PATIENT TO GO. If the movement comes out wrong, the diagnosis is usually your hand position or an imprecise verbal cue, not the patient."));
k.push(h1("Functional Applications"));
k.push(compare("UPPER extremity","LOWER extremity",
 ["**D2 flexion**: lifting and reaching overhead, rolling, dressing. **D2 extension**: reaching down and across the body, rolling sidelying to sitting, pushing down across midline (bed mobility), **overhead throwing** — tennis, football, baseball — and pulling the passenger-side seat belt down and across. **D1** is the driver-side seat belt: reach across, pull down, buckle. Both patterns are excellent for **glenohumeral and scapular neuromuscular stability**."],
 ["**D1 flexion**: kicking a soccer ball (the follow-through across the body), moving supine to prone (“bend your knees up”), crossing the foot over the opposite knee to put on a shoe. **D1 extension**: the wind-up of a soccer kick, putting a leg into pants, rolling prone to supine, the uncrossing leg in a karaoke/crossover step. **D2 flexion**: an outward karate kick, the heels-up phase of a breaststroke. **D2 extension**: **push-off in gait**, the heels-down kick of a breaststroke, the crossing leg in a karaoke step."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(bullet("**Where to use them**: **supine** is how you learn them, and it's genuinely useful — hands on the patient let you feel exactly where in the range they're weak or uncoordinated and deliver feedback at that point, which suits early healing stages and works well even for overhead athletes. **Standing** patterns become an exercise in their own right: general strengthening against gravity, coordination and neuromuscular training, sport-specific movement, and a **built-in balance challenge** because the stance limb holds single-limb support while the other moves through the diagonal. Add free weights or bands as tolerated (bands are logistically awkward for some LE patterns). Naming with resistance: **name the direction receiving the resistance** — “resisted upper extremity D2 flexion.”"));

/* ─────────────── STUDY ─────────────── */
k.push(pageBreak());
k.push(banner("MODULE 7","Reading Map, Lab Prep, and Glossary"));
k.push(spacer());
k.push(detail(["Topic","Source"],[
 ["Regional guidelines","General Exercise Guidelines lectures 7.1 (spine) through 7.7 (ankle/foot) by Dr. Shaw + slides; **Kisner & Colby ch. 15–22** — especially **boxes 15.1–15.3, 16.1–16.2 and tables 16.1–16.3**"],
 ["PNF","Intro to PNF, UE D1, UE D2, and LE Patterns lectures by Dr. Mierau + the **Clinical Practice PNF Philosophy & Principles** and **PNF Patterns** handouts; **PhysioU videos**"],
 ["Lab","**TI 2 Lab Manual 2026** + combined Modules 6 and 7 skills list (module folder). Lab immersion **March 30 – April 1**: day 1 physical agents/modalities, day 2 treatment interventions, **day 3 practical exam**"],
 ["Assessment","Quiz 5 · Case Study #2 · final exam · lab practical (20% of the grade)"]],[2400,6960]));
k.push(tnote("Dr. Mierau's homework, and it is the right advice: practice the diagonals on somebody at home BEFORE lab. Run a full rhythmic initiation — passive, then active-assisted, then active, then add resistance — and practice the hand placements and the verbal cues out loud. If the patient does something other than what you asked, work out why: wrong hand position, or a cue that wasn't sharp enough. Showing up to lab having never touched a limb means spending lab learning which pattern is which instead of refining technique."));
k.push(spacer());
k.push(...glossary("Module 7 Quick-Reference Glossary",[
 ["The five areas","Kinesthetic awareness · mobility and flexibility · muscle performance and motor control · cardiopulmonary endurance · functional activities"],
 ["The three rehab phases","Protection (acute) → controlled motion (subacute) → return to function (chronic)"],
 ["Spinal biases","DJD and tension headache = flexion · herniated disc and compression fracture = extension"],
 ["Protrusion vs extrusion","Displaced material continuous with the disc, base wider than what enters the canal vs beyond that"],
 ["Relative rest","Limit activity on the worst days — but bed rest beyond two days is not recommended and complete inactivity worsens back pain"],
 ["Lumbar lordosis reduction","Pelvic tilts in multiple positions — excess lordosis loads the posterior elements and facets"],
 ["Stabilization sequence","Kinesthetic awareness (neutral spine, head nods, pelvic tilts) → deep segmental activation (drawing-in, cranio-cervical flexion) → global control → functional training"],
 ["Progressive limb loading","Max protection: 90° flexion/abduction · moderate: end range · minimal: diagonal patterns"],
 ["Scapulohumeral rhythm","Preserves glenohumeral length-tension and force production; 3 motions + 2 translations"],
 ["Winging vs dyskinesia","Serratus anterior weakness/paralysis specifically vs the broader category of abnormal scapular motion"],
 ["Swan neck vs boutonnière","PIP hyperextension with DIP flexion vs PIP flexion with DIP extension (ruptured central slip)"],
 ["Knee effusion position","~25° flexion is most comfortable; distension reflexively inhibits the quadriceps"],
 ["Immediate vs delayed knee swelling","Immediate = bleeding · >4 hours = serous effusion"],
 ["Cane rule","Assistive device in the hand OPPOSITE the painful hip"],
 ["PNF","Functional diagonal patterns + neuromuscular facilitation; usable at every stage of healing"],
 ["Naming rule","Name the diagonal for where the SHOULDER or HIP ends — flexion or extension"],
 ["UE imagery","D1 = seat belt · D2 = sword/disco"],
 ["LE imagery","D1 = hacky sack / bike kickstand · D2 = doggy position / crossed-behind leg"],
 ["Manual contacts","Over the agonist; one distal (movement starts here), one proximal"],
 ["Maximal resistance","As much as the patient can control pain-free — not as much as you can give"],
 ["Stretch stimulus","Lengthen the muscle about to contract; quick stretch is NOT for acute stages"],
 ["Normal timing","Distal to proximal sequencing"],
 ["Rhythmic initiation","Passive → active-assisted → active → resisted"],
 ["Repeated contractions","Quick stretches + resistance through range to strengthen a weak agonist at a specific point"],
 ["Slow reversal / slow reversal hold","Agonist immediately into antagonist with no rest / plus an isometric hold at each end"],
 ["Alternating isometrics vs rhythmic stabilization","Single-plane resistance side to side while holding vs multidirectional simultaneous resistance in weight-bearing"],
 ["Hand-placement principle","Put your hands where you want the patient to GO"],
 ["Resisted pattern naming","Name the direction receiving the resistance (e.g. resisted UE D2 flexion)"]]));

build(k,"/home/claude/out/TI2_Module7_ExerciseGuidelinesAndPNF_StudyNotes.docx");
