const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const k=[];

k.push(...cover("Musculoskeletal Practice I (DPTH 6412)","Final Exam Study Guide",
 "The official Module 7 concept list, expanded — every line mapped to the answer and the module notes where it lives",
 ["Faculty published this exact concept list (Sync 7 handout) — if it's on this page, it's fair game; if you can answer every line from memory, you're ready",
  "★ Assignments due this module: 3-Minute Drill #2 — rehearse explaining a diagnosis + plan in plain language (Lucy and Sarah from Sync 6 are ideal practice)",
  "After the final: 3-day lab immersion at the NCS"]));

k.push(banner("CONCEPT LIST","Every Line, With the Answer Attached"));
k.push(spacer());
k.push(h1("Module 1 — Clinical Reasoning & Screening"));
k.push(bullet("**SINSS**: Severity (intensity/function impact) vs Irritability (how easily provoked + how long to settle — drives exam/treatment dose) vs Stability (better/worse/same trajectory). **Biases**: anchoring (stuck on first impression) + confirmation (only collecting agreeing evidence) — counter by testing the hypothesis you DON'T hold. **Neuro screen**: myotomes L3 knee extension · L4 dorsiflexion · L5 great-toe extension · S1 plantarflexion/eversion; **SLR positive ≈ <40°** with distal symptom reproduction. **Red flags**: unexplained weight loss (+ night pain, fever, saddle anesthesia, bowel/bladder). **Outcome measures**: STarT Back risk-stratifies low/medium/high (high → psychologically-informed care); ODI 0-100% disability. **Spondylolisthesis**: extension-provoked pain, palpable step-off, adolescent extension athletes (Module 1 notes, bony pathology section)."));
k.push(h1("Module 2 — LBP Assessment"));
k.push(bullet("**Directional preference + lateral shift**: repeated-movement testing; correct the shift BEFORE extension. **Centralization** (distal pain retreats proximally = good, treat that direction) vs **peripheralization** (spreads distally = wrong direction). **CPG classifications**: mobility deficit · movement-coordination impairment (MCI) · referred (back > leg) · radiating (leg > back, nerve signs). **Neurogenic vs vascular claudication**: neurogenic eases with FLEXION/sitting and tolerates the bike; vascular eases with standing STILL and hates the bike regardless of posture; pulses + skin round it out. **Mobility testing**: PA spring testing for segmental mobility + provocation; ROM with quality/aberrance. **MCI**: Panjabi's passive-active-neural control systems; aberrant movements (painful arc, Gower's sign/thigh climbing, instability catch, reversed lumbopelvic rhythm)."));
k.push(h1("Module 3 — LBP Intervention"));
k.push(bullet("**Best evidence = exercise + education** (the exercise the patient will DO; acuity-matched education — reassurance early, pain neuroscience + active care chronic). **McKenzie/directional preference** for disc/referred pain: matched exercise = 7.8× better odds. **Irritability gates treatment**: high → symptom-modulation, short levers, low dose; low → load toward capacity. **Sliders** (one end slack — gentler, subacute) vs **tensioners** (both ends — stronger, chronic). **Manipulation indications** (2007 CPR): <16 days, nothing distal to the knee, hypomobility, low FABQ, hip IR >35°. **Acuity matching**: acute = motion is lotion + directional preference; subacute = regional interdependence (thoracic/pelvis/hips); chronic = graded activity/exposure, aerobic dosing (>50% VO2max >10 min for exercise analgesia)."));
k.push(h1("Module 4 — MCI, Surgery, SI Joint"));
k.push(bullet("**MCI ladder**: Activation (find + fire TrA/multifidus with breath) → Acquisition (dissociate limbs while braced) → Assimilation (into function/sport). **Motor control vs strength**: timing/coordination at low load first — a strong global system can't rescue an uncoordinated deep one. **Surgery**: microdiscectomy (herniation → radiculopathy; fastest recovery; discs can also regress spontaneously — 96% sequestered/70% extruded/41% protruded/13% bulge) vs laminectomy/decompression (stenosis) vs fusion (instability/deformity — ALIF/PLIF/TLIF menu). **Post-op ~6 weeks BLT**: no Bending, no Lifting >10 lb, no Twisting. **SIJ testing = clusters, not single tests**: Laslett 2/4 (or 3/6) provocation tests after a centralization veto (centralizers aren't SIJ); motion palpation (Gillet, standing flexion) is unreliable. **Form closure** (bony/ligamentous fit, nutation locks) vs **force closure** (muscle slings compress — train it when hypermobile: slings + pelvic floor ± SI belt)."));
k.push(h1("Module 5 — Pelvic Floor & Hip"));
k.push(bullet("**Pelvic floor anatomy + palpation**: levator ani (puborectalis/pubococcygeus/iliococcygeus) + coccygeus; external palpation medial to the ischial tuberosity (tuberosity-biased = obturator internus, midline-biased = levator ani); contract-relax-cough-bear-down. **Pudendal nerve**: pudendal canal; neuralgia = saddle/perineal pain (Roger's case — cyclist, sitting-provoked). **Diaphragm-pelvic floor relationship**: reciprocal motion — inhale descends both, the treatment lever for an overactive floor. **Hip OA (2017 CPG)**: IR <24°, IR + flexion 15° less than the other side, morning stiffness <1 h, anterior/lateral weight-bearing pain, pain on passive IR. **THA posterior precautions**: no flexion >90°, no adduction past midline, no IR. **Wells DVT**: one point each (recent surgery, tenderness, swelling, calf >3 cm, pitting edema, collaterals, prior DVT, cancer, immobilization; -2 alternative diagnosis); **≥2 = likely** — document it on every post-op patient."));
k.push(h1("Module 6 — Hip Pathology & Advanced Cases"));
k.push(bullet("**FAI/labral**: anterior/groin pain (C-sign), ↓IR + flexion (IR <20° at 90° flexion is the risk flag), squat-depth loss improving with ER. **FADIR**: flexion-adduction-IR reproducing groin pain = the impingement test. **Post-op arthroscopy**: phase-based; 20% FFWB ×2 wk (microfracture 6 wk), NO early ER, circumduction, posterior/inferior glides only, no running before 12 weeks, Vail pass = 46/54. **Extra-articular**: iliopsoas snapping hip (coxa saltans interna — snap over the femoral head with flexion-extension; modify the arc, then strengthen); GTPS = strengthen abductors + decompress, don't stretch. **Special tests**: FABER (≈20 cm knee-to-table; SIJ vs hip localization), FADIR, **Thomas** (iliopsoas/rectus/TFL length — leg drops short of table = flexor tightness)."));
k.push(tip("Exam-week plan: one module per pass, this page as the checklist. For every line ask: can I (1) define it, (2) name the number attached to it, and (3) say what I'd DO with it in clinic? The final loves the numbers — 40° SLR, 16 days, 7.8×, 6 weeks BLT, 24°, 90°, 2 on Wells, 46/54."));

build(k,"/home/claude/out/MSK1_FinalExam_StudyGuide.docx");
