const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const k=[];

k.push(...cover("Therapeutic Interventions II (DPTH 6241)","Module 6: Preoperative Care, Postoperative Management, and Peripheral Nerve",
 "Topics 6.1–6.5: Preoperative Care · Common Surgical Procedures · Post-Op Examination and Phases · Complications and Risk Reduction · Post-Op Interventions • Topics 6.6–6.9: Impaired Nerve Function · PNI Classification and Management · Neurodynamic Disorders · Common MSK Syndromes",
 ["Watch the lectures in your own Canvas module — these notes condense them, they don't replace them",
  "★ Dr. Awruch's sync-session motto for this module: PROTECT FIRST. PROGRESS SECOND. FUNCTION ALWAYS.",
  "The decision loop, again: goal → safety screen → best next step → re-test → progress, hold, or regress"]));

/* ─────────────── 6.1 PREOP ─────────────── */
k.push(banner("TOPIC 6.1","Preoperative Care — Purposes and Goals"));
k.push(spacer());
k.push(infoBox("Why prehabilitation earns its place",["A meta-analysis of RCTs found prehabilitation (**education + exercise**) improves outcomes after total joint surgery. **Total hip**: less post-op pain, improved post-op function, shorter length of stay. **Total knee**: improved post-op function, **greater quadriceps strength**, shorter length of stay."],C.green,C.lightGreen));
k.push(bullet("**Indications for surgery** (conservative care is always tried first): incapacitating pain at rest or with activity · marked motion limitation · gross joint or bony instability · deformity or abnormal alignment · significant structural degeneration · chronic joint swelling · failed non-surgical OR previous surgical management · significant loss of function leading to disability. **Common procedures you'll rehab**: total joint replacements, ligament laxity repairs, tendon repairs, nerve releases, spinal repairs and corrections."));
k.push(detail(["Pre-op element","What you do"],[
 ["**Examination for a BASELINE**","**Pain** (VAS or a scale tied to specific functional activities) · **ROM and joint integrity** (A/PROM, quality of active motion, accessory mobility and special tests for stability) · **Integument** — skin integrity and old scars, especially adherent ones; a **keloid** history predicts keloid risk again, so plan for it · **Muscle performance** — strength of the affected area (remembering pain makes people test weak) PLUS the **unaffected segments**, in anticipation of crutch-walking, transfers, and ADLs · **Posture** and preferred positions of comfort · **Gait** with current devices and weight-bearing status · **Functional status** and the patient's own perception of disability"],
 ["**Patient education**","One-on-one is best; a **group setting** is often the practical answer when reimbursement for individual pre-op consults is hard to get. Cover: overview of the plan of care and post-op expectations · **post-op precautions and contraindications** for positioning, movement, and weight-bearing (think hip precautions) · bed mobility and safe transfers with those precautions built in · **deep breathing and coughing exercises** (surgery carries pneumonia and bronchitis risk) · gait training · wound care · pain management · home and work safety"],
 ["**Pre-op exercise**","**Ankle pumps** — taught before surgery so they're remembered after — to reduce venous stasis and DVT risk · gentle **muscle setting** isometrics · plus modalities (ice, heat, e-stim, ultrasound), manual therapy, strength, ROM and transfer training. Goal: enter surgery in the best possible condition"]],[2400,6960]));
k.push(bullet("**Benefits of pre-op communication**: assess baseline functional status, discuss goals and expectations, **establish rapport, minimize anxiety**, and educate about the rehab to come — which limits the progression of post-op impairments, improves exercise familiarity and execution, and improves the odds of functional recovery."));

/* ─────────────── 6.2 SURGERIES ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.2","Common Surgical Procedures"));
k.push(spacer());
k.push(detail(["Graft type","Source · risk · example"],[
 ["**Autograft**","The patient's own tissue from a donor site. Risk: **two surgical sites**, and infection or complication at the donor site. Example: **patellar tendon for ACL/PCL reconstruction**; harvested skin for burns"],
 ["**Allograft**","Fresh or cryopreserved tissue from another source, usually cadaver — used when autograft isn't available or has failed. Risks: **disease transmission, graft strength compromised by sterilization, immunological rejection**. Example: bone graft in spinal fusion"],
 ["**Synthetic**","Gore-Tex or Dacron when human tissue isn't an option. Risks: **high failure rate, chronic synovitis** (notably in the knee). Example: vascular graft"]],[2400,6960]));
k.push(compare("MUSCLE repair","TENDON repair",
 ["Complete rupture is unusual — happens when a contracting muscle takes a direct blow or is forcibly stretched. **Surgery is DELAYED 48–72 hours**, because inflammation changes the tissue texture and sutures won't hold. Repaired muscle is re-apposed, sutured, and **immobilized SHORTENED**. Rehab: gradual **low-force muscle setting (isometrics only)** → after immobilization, AROM within a protected range → restore joint mobility → **low-load, high-rep, pain-free** resistance, progressed gradually. **Vigorous stretching and full return are contraindicated until healing is complete — 6 to 8 weeks.**"],
 ["Trauma in the young, degeneration with age, or both plus a forceful load — usually at the **musculotendinous or tendo-osseous junction** (classic sites: bicipital tendon, Achilles). **Repair IMMEDIATELY** — a delayed tendon retracts and becomes hard to reattach. Held **shortened**, with a **LONGER immobilization than muscle repair**. But get it moving: **gentle low-force muscle setting can begin immediately** to prevent adhesion of tendon to sheath and to align healing tissue. Controlled antigravity motion after several weeks; weight-bearing may be restricted; **heavy lifting contraindicated 6–8 weeks**; vigorous stretching and high-intensity resistance wait **at least 8 weeks**. Because it was held short for weeks, **regaining full ROM is the hard part** — make it the focus."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(detail(["Procedure","Key points for rehab"],[
 ["**Ligament repair vs reconstruction**","Repair approximates and sutures the torn ends; **reconstruction uses a graft**. Knee, ankle, elbow most common. Post-op management is lengthy and depends on repair type and site (see the ACL protocol in the module folder)"],
 ["**Capsule stabilization / reconstruction**","For traumatic dislocation with capsular or labral avulsion or fracture, recurrent dislocation or symptomatic subluxation despite conservative care, or an irreducible dislocation. Balance **stability against functional motion**: active motion in a protected range early, **cautious progression of any movement stressing the repaired portion of the capsule**, then strengthening that emphasizes **dynamic stabilizers**"],
 ["**Tendon transfer / realignment**","Alters the **line of pull**, and therefore force generation. **Realignment changes the line of pull but NOT the muscle's action; a TRANSFER changes both.** When the action changes, **biofeedback and electrical stimulation** help the patient learn the new movement. Early muscle setting and protected motion maintain tendon gliding; resistive work progresses cautiously"],
 ["**Soft tissue release**","Myotomy, tenotomy, fasciotomy to improve ROM, prevent deformity, or relieve pain. **CPM and/or AAROM within a day or two**, then AROM through the gained range, with **early strengthening of the ANTAGONISTS of the lengthened muscle** to control the new range"],
 ["**Joint debridement / lavage / synovectomy**","Arthroscopic removal of fibrillated cartilage, chondral flaps, loose fragments; osteophytes may be excised; usually for pain, clicking, catching. **Arthroscopic: PROM/AAROM or CPM plus muscle setting within 24 hours**, quickly to AROM. After knee synovectomy: PWB → **full weight-bearing by 10–14 days**; wrist or elbow synovectomy restricts heavy lifting for weeks; **open synovectomy progresses more slowly**. Avoid any exercise that increases joint pain or swelling"],
 ["**Articular cartilage procedures**","**Abrasion arthroplasty/chondroplasty and subchondral drilling** — questionable benefit, possibly no better than debridement alone. **Microfracture** repairs defects **<1.5 cm**. **Autologous chondrocyte implantation** stimulates hyaline cartilage growth. **Osteochondral grafts** transplant cartilage with underlying bone. Rehab is **slow and arduous**: early passive motion (often CPM) and protected weight-bearing to keep implanted chondrocytes healthy; **FWB by 6–8 weeks**; progressive program continues **6 months to a year**"],
 ["**Excision / interposition arthroplasty**","Implant resection arthroplasty inserts a flexible silicone implant that becomes encapsulated as the joint reforms. **Interposition** places material (fascia, tendon, silicone, metal) between debrided surfaces — used in **younger patients** with severe surface deterioration who aren't candidates for replacement"],
 ["**Joint replacement**","**Total** replaces both articular surfaces; **hemi** replaces one — used when only one surface has deteriorated and after femoral neck or proximal humeral fracture. Early ROM, strengthening, modalities, manual therapy"],
 ["**Arthrodesis (fusion)**","Surgical fusion for severe pain with late-stage arthritis and instability **where mobility matters less than stability**; also for significant muscle weakness from neurological causes (peripheral neuropathy at the ankle, severe brachial plexus injury) and as a **salvage** after failed arthroplasty when revision isn't an option"],
 ["**Extra-articular bony procedures + osteotomy**","Fixation maintains fracture-site stability for bony healing; progression depends on fracture type and severity, patient age and health, and the fixation method (some eliminate the need for external stabilization, some don't). **Osteotomy** cuts and realigns bone to **shift weight-bearing loads to intact surfaces**, reducing pain, slowing cartilage deterioration, possibly stimulating fibrocartilage growth in the unloaded compartment — used in **younger patients to DELAY joint replacement** and the revision that would follow"]],[2400,6960]));

/* ─────────────── 6.3 PHASES ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.3","Post-Operative Examination and the Three Phases"));
k.push(spacer());
k.push(bullet("**Before you design anything**, you need: the indications and rationale for the procedure, working familiarity with what was actually done, the surgery-specific precautions, and the ability to communicate with the patient, the surgeon, and the team. **Integumentary assessment is paramount at every visit**: redness or tissue necrosis along the incision and near sutures, tenderness and edema on palpation, increased heat, **drainage (note color and amount on the dressing)**, integrity of an incision crossing a joint during and after exercise, and **scar mobility** to catch adhesions early."));
k.push(detail(["Phase","Timing · criteria · goals"],[
 ["**MAXIMUM protection**","**A few days to 6 weeks** depending on procedure and tissue. Protection is paramount — tissue disruption, inflammation, and pain. Some surgeries require early mobilization; others allow **low-level stress soon after surgery** with early passive or assisted ROM in a protected range. **Muscle setting in both cases** to limit disuse atrophy. Goals: educate on safe positioning, precautions, and contraindications · **decrease pain** (modalities, CPM) · **prevent wound infection** (cleaning, dressing) · **minimize swelling** (elevation, ankle pumps/muscle pump, compression garment, low-level massage) · **prevent circulatory and pulmonary complications** (the coughing and breathing exercises you taught pre-op) · prevent joint stiffness and atrophy · maintain motion and strength **above and below** the surgical site · maintain function with adaptive equipment and assistive devices"],
 ["**MODERATE protection**","Typically **begins ~4–6 weeks post-op and continues another 4–6 weeks**. Criteria to enter: **no pain at rest** and at least limited pain-free movement of the operated extremity. Inflammation has subsided; tissue tolerates gradually increasing stress. Goals: educate to **back off if pain or swelling appears** · **scar management** (teach scar mobilization; cross-friction massage) · restore soft tissue and joint mobility — AROM within pain limits, **grade 1–2 mobilizations for pain, grade 3–4 to regain range** · begin strengthening and joint stability: **alternating isometrics** (remembering an isometric only strengthens at the angle trained), so add **concentric** work — **not eccentric yet** — plus **rhythmic stabilization** (PNF), dynamic open- and closed-chain exercise, and functional activity"],
 ["**MINIMAL protection / return to function**","**Begins 6–12 weeks post-op and may continue to 6 months or beyond.** Criteria: **full or near-full pain-free AROM and joint stability** (strength requirements vary widely by procedure). Focus: restoring functional strength and progressively advancing functional activities"]],[2400,6960]));
k.push(tip("Post-op precautions to carry into every session: don't re-injure or reopen the incision · avoid positions, movements, or weight-bearing that compromise the repair · keep the wound clean and monitor drainage and signs of local or systemic infection · AVOID VIGOROUS HIGH-INTENSITY STRETCHING OR RESISTANCE FOR AT LEAST 6 WEEKS on repaired or reattached muscle, tendon, or capsule · and modify activity level and type to prevent premature loading of reconstructed tissue."));

/* ─────────────── 6.4 COMPLICATIONS ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.4","Post-Operative Complications and Risk Reduction"));
k.push(spacer());
k.push(bullet("**The complication list to stay alert for**: pulmonary dysfunction (**pneumonia, atelectasis**) · local or systemic **infection** · **DVT and pulmonary embolism** · delayed wound healing · muscle deficits from ischemia or **tourniquet-related nerve compression** · failure, loosening, or displacement of internal fixation · delayed union after fracture, osteotomy, or fusion · rupture or incomplete healing of repaired soft tissue · subluxation or dislocation of joint surfaces or implants · **nerve entrapment from scar tissue** causing pain or sensory change · adhesions and scarring → contracture and joint hypomobility · implant loosening from periprosthetic osteolysis or infection."));
k.push(detail(["Category","Factors"],[
 ["**Independent risk factors**","Post-op or post-fracture **immobilization** · prolonged bed rest · sedentary lifestyle or extended sitting pre-op · **prolonged standing >6 hours** · trauma to venous vessels · limb paralysis · **active malignancy within the past 6 months** · prior DVT or PE · advanced age · obesity · congestive heart failure · **oral contraceptive use** · multiple pregnancies"],
 ["**Triggering factors**","Pregnancy · violent or high-exertion effort · muscle trauma · immobilization · **long-distance travel (compression garments for flights over ~8 hours)** · infectious disease"],
 ["**PE symptoms**","Syncope · wheezing · dull chest pain · calf or leg pain · cough · **hemoptysis** · dyspnea. Any combination raises suspicion; all of them together is high risk"]],[2400,6960]));
k.push(infoBox("Wells criteria for DVT — score and act",["One point each: **active cancer · immobility >3 days or major surgery <4 weeks** (every post-op patient starts here) **· calf swelling >3 cm vs the other leg · collateral non-varicose superficial veins · entire leg swollen · localized tenderness along the deep venous system · pitting edema greater in the symptomatic leg · paralysis, paresis, or recent cast immobilization · previously documented DVT.** Subtract 2 if an alternative diagnosis is as likely or more likely. **0 = low risk · 1–2 = moderate · ≥3 = high risk.**"],C.red,C.lightRed));
k.push(bullet("**DVT management**: **bed rest and pharmacological management with a systemic anticoagulant during the acute inflammatory period — you CANNOT mobilize the patient before therapeutic anticoagulation**, because movement can dislodge the clot into a PE. Elevate the affected leg with **slight knee flexion**. Once anticoagulation is therapeutic, begin mobility, progressively increasing ambulation and functional training **in graded compression stockings**. Then prevent recurrence: continued medical management plus keeping the patient moving."));
k.push(compare("CONTRAINDICATED with DVT/thrombophlebitis","PRECAUTIONS after discharge",
 ["**Passive OR active range of motion** · **moist heat** · **sequential pneumatic compression pump** (e.g. JOBST). All three can dislodge the clot."],
 ["While still on anticoagulant medication: **avoid contact sports and any activity with a high risk of falling or trauma** — the bleeding risk is the issue now."],
 C.red,C.blue,C.lightRed,C.lightBlue));

/* ─────────────── 6.5 + NERVE INTRO ─────────────── */
k.push(pageBreak());
k.push(banner("TOPICS 6.5 & 6.6","Post-Operative Interventions · Impaired Nerve Function"));
k.push(spacer());
k.push(bullet("**Post-op interventions**: treat surgery **like an acute injury** — there is a wound healing externally and repaired tissue internally — so recognize the phase of tissue healing, read the symptoms, and pick the modality that matches (Cameron's clinical decision-making tables for acute injury and therapeutic effect are the tools to keep on hand). **Exercise selection depends on the procedure, the joint, and the surgical approach.** Follow the surgeon's protocol where one exists — some surgeons hand the progression to the PT, but disrupting a repair you were given a protocol for is a different conversation than disrupting one you improvised."));
k.push(h1("Mechanisms and Sites of Peripheral Nerve Injury"));
k.push(bullet("**Why nerves hurt**: the connective tissue and vascular structures surrounding peripheral nerves are themselves innervated, and **nerve function is sensitive to hypoxia**. **Mechanisms**: compression (median nerve in the carpal tunnel) · laceration · **stretch** (contact collisions) · **radiation** (dropped head syndrome — neck extensor weakness) · electricity (lightning) · **injection palsy** (radial nerve below the deltoid; axillary nerve at the side of the deltoid). Biomechanically it comes down to **friction, compression, and stretch**, with secondary injury from blood or edema. Compression affects **microcirculation → venous congestion → reduced axoplasmic transport → blocked impulses**, and sustained compression damages the nerve."));
k.push(compare("INTRANEURAL injury","EXTRANEURAL injury",
 ["Pathology affecting the **conducting tissues** (hypoxia, demyelination) or the nerve's own **connective tissue** (scarring of the epineurium, irritation of the dura mater) — restricting the **elasticity of the nervous system itself**."],
 ["Pathology affecting the **nerve bed**: blood, **adhesion of the epineurium to adjacent tissue** such as a ligament, or swelling of tissue next to the nerve such as foraminal stenosis — restricting the **gross movement of the nerve relative to surrounding tissue**."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(detail(["Nerve","Course, injury mechanism, and deficit"],[
 ["**Axillary**","Posterior cord → through the axilla → branch to teres minor → **behind the surgical neck of the humerus** → deltoid and overlying skin. Injured by **shoulder dislocation and surgical neck fractures**, or upper trunk stretch → impaired **shoulder abduction and external rotation**"],
 ["**Musculocutaneous**","Lateral cord → crosses the axilla with the median → pierces coracobrachialis → biceps and brachialis. Lateral cord/upper trunk injury → **inability to flex the elbow with the forearm supinated**, possible shoulder instability"],
 ["**Median**","Medial humerus → deep in the cubital fossa under the bicipital aponeurosis → **between the two heads of pronator teres**. **Pronator teres hypertrophy mimics carpal tunnel EXCEPT the forearm muscles are also involved.** Entrapment in the tunnel = **carpal tunnel syndrome** — sensory change and progressive weakness distal to the wrist"],
 ["**Ulnar**","Highly mobile around the elbow but superficial — irritated or entrapped there as **cubital tunnel syndrome** (the funny bone), then between the humeral and ulnar heads of **flexor carpi ulnaris** (another entrapment site). Extrinsics: FCU and the **ulnar half of flexor digitorum profundus**. Enters the hand through the **tunnel of Guyon** → entrapment causes sensory change and progressive weakness distally with a **partial claw hand**"],
 ["**Radial**","Triceps, anconeus, forearm extensor-supinator group. Injured with **shoulder dislocation and midshaft humeral fracture**; **crutch palsy** (leaning on axillary crutches); **Saturday night palsy** (sleeping with the arm over a chair back or car window) — **triceps involved only if compression is near the axilla**. Deep branch entrapment under extensor carpi radialis brevis and the fibrous slit of supinator → progressive wrist/finger extensor and supinator weakness, **sometimes mislabeled tennis elbow**; can also be injured with a **radial head fracture**. Injury proximal to the elbow → **wrist drop**, ineffective grip unless the wrist is held in partial extension"],
 ["**Femoral**","Injured by upper femur or pelvic fracture, reduction of congenital hip dislocation, or **forceps delivery pressure** → weak hip flexion and **loss of knee extension**; neuritis in diabetes mellitus"],
 ["**Obturator / sciatic**","Isolated obturator injury is rare (uterine pressure in labor) → impaired **adduction and external rotation**, trouble crossing the legs. **Piriformis syndrome** compresses the sciatic nerve; sciatic injury also occurs between the ischial tuberosity and greater trochanter with hip dislocation or reduction"],
 ["**Tibial (posterior)**","Entrapment from a space-occupying lesion = **tarsal tunnel syndrome**; the plantar and calcaneal branches can be entrapped under the medial foot passing through openings in **abductor hallucis**, especially with **overpronation** → symptoms like acute foot strain, painful heel, clawing of toes, pes cavus"],
 ["**Common fibular**","Compressed **around the fibular neck** through an opening in fibularis longus — also injured by fibular head fracture, LCL rupture, or a tight cast, and by **leg-crossing (the foot 'falling asleep')**. **Superficial branch** → fibularis longus and brevis; isolated injury affects **eversion**, and over time **equinovarus** develops from unopposed inversion. **Deep branch** → dorsiflexors, toe extensors, fibularis tertius, extensor digitorum brevis; injury causes **foot drop** with unopposed eversion in gait, and over time pes valgus"]],[2200,7160]));

/* ─────────────── 6.7 CLASSIFICATION ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.7","Classification and Management of Peripheral Nerve Injury"));
k.push(spacer());
k.push(bullet("**Two classification systems, used interchangeably: SEDDON and SUNDERLAND.** Both grade the injury by **how deep it goes** — epineurium, perineurium, endoneurium, axon, and basal lamina. **Examination focus** for a nerve-injured patient: pain assessment · sensory deficit and skin condition · muscle strength and loss · functional and balance deficits · joint stiffness · and **the emotional stress of losing function**, which is not a footnote."));
k.push(detail(["Phase","Management"],[
 ["**ACUTE — protect**","**Pain and edema management, orthosis management, movement, education.** Immobilization may be ordered for **several days up to 3 weeks** to protect the nerve, minimize inflammation, and minimize compression or traction — the orthosis and its position depend on the nerve, and the duration on the injury and repair. Meanwhile: **active movement of the uninvolved side immediately**, gentle ROM of uninvolved joints to prevent contracture, then the involved side as healing allows. Orthoses also **prevent deformity** from denervated muscle (claw hand, ape hand). **Education**: safe movement, protecting the nerve, and **frequent visual inspection of insensate areas**"],
 ["**Acute pain toolkit**","Contrast baths · **desensitization** · edema control · electrotherapy. **TENS has evidence in painful peripheral neuropathy: ACUTE — up to 1 hour/day at 80–120 Hz; CHRONIC — up to 30 min/day at 2–10 Hz.** Low-level laser may help neuropathic pain. Elevation, compression, medication, massage. **E-stim for edema**: pulsed current set for contract-relax to drive the muscle pump"],
 ["**RECOVERY — retrain**","Begins **with signs of re-innervation**: some voluntary contraction, but **hypersensitivity**, and re-innervated muscle is **weaker and fatigues faster**. Work on motor retraining, desensitization, **discriminative sensory re-education**, and continued education. **Strengthening must not damage healing nerve — pins and needles, numbness, or increased pain with exercise means the dose is too hard.** Progress conservatively: **isometric → graded weighted exercise → open and closed chain**, adding balance work as appropriate"],
 ["**CHRONIC — compensate**","Train compensation for function that hasn't returned; **supportive orthoses and preventive care continue indefinitely**. Mobilization splints (dynamic, static progressive, serial static) substitute for weak or absent muscles while preserving passive motion — e.g. a **radial nerve splint** using rubber-band traction or a static line to substitute for absent extrinsic extensors"]],[2400,6960]));
k.push(bullet("**Desensitization** — stimulate the affected area regularly with pinching, tapping, brushing, icing, massage, rubbing with towels and cloth, or dipping the hand or foot in **rice, macaroni, or sand**. With **vibration**, follow the nerve's actual recovery order: **slow vibration (~30 CPS) → touch with the vibrating wand → constant touch → rapid vibration (~250 CPS)**, working **proximal to distal** (start at the elbow for a hand injury). **Sensory re-education / retraining the brain**: moving touch stimulus (a pencil eraser) over the area — patient watches, then closes their eyes and localizes it → progress from stroking to constant touch → then identification of familiar objects of varied size, shape, and texture (keys, coins, utensils, toothbrush for the hand; grass, sand, pebbles, uneven surfaces for the feet). **Proprioception**: balance board, vibration-based somatosensory training, joint repositioning, mirror work, exercise balls, AirEx pads, juggling, yoga, tai chi."));
k.push(tnote("Two techniques worth knowing by name because they recur across the curriculum: MIRROR THERAPY and GRADED MOTOR IMAGERY — movement representation techniques with support in neuropathic pain management, especially phantom limb pain. And don't skip aerobic exercise: regular aerobic work helps manage chronic pain and may aid nerve recovery (there's evidence in chemotherapy-induced neuropathic pain), partly through stimulation of the endogenous opioid system — exercise-induced analgesia, the runner's-high mechanism put to clinical use."));

/* ─────────────── 6.8 NEURODYNAMICS ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.8","Neurodynamic Disorders and Nerve Mobility Testing"));
k.push(spacer());
k.push(infoBox("General rules for every neurodynamic test",["Explain the procedure in **lay terms** first — anticipation makes patients tense. Tell them it may or may not evoke symptoms and to **speak up at any discomfort**. **Evoke, don't aggravate.** **Test the asymptomatic side FIRST.** Precision comes from a stable stabilizing hand and a **slow, steady** mobilizing hand. **Hold the final position no longer than 10 seconds.** Watch for unwanted movement that alters the result. Upper limb joint order: **shoulder → forearm → wrist → fingers → elbow**, adding components until symptoms reproduce; **if pain comes at the initial position, stop — no sensitizers needed**."],C.gold,C.lightGold));
k.push(bullet("**A positive test** = symptoms reproduced, **OR side-to-side difference in elbow extension greater than 10°**, **OR contralateral cervical side-bending increases symptoms / ipsilateral side-bending decreases them**. That third criterion is the sensitizer response, and it's what separates a real neurodynamic finding from a stretch sensation."));
k.push(detail(["Test","Nerve · when to use · sequence"],[
 ["**ULNT 1 — MEDIAN**","For radiating upper limb pain or **tingling in the first three fingers**. Shoulder **depression** → abduction to **110°** → external rotation with the elbow at 90° → forearm **supination** → wrist and finger extension → **elbow extension**. Proximal symptoms ease with wrist/finger extension; provoke distally with contralateral neck flexion"],
 ["**ULNT 2B — RADIAL**","For radiating pain, **supinator tunnel syndrome**, cervical radiculopathy. Shoulder girdle depression → abduction **20–30°** → **internal** rotation → forearm **pronation** → wrist, finger, and thumb **flexion** → elbow extension"],
 ["**ULNT 3 — ULNAR**","For pain radiating to the **4th and 5th digits**, thoracic outlet syndrome, carpal tunnel syndrome. Shoulder depression → abduction **110°** → external rotation → forearm **pronation** → wrist and finger extension → **elbow FLEXION**"],
 ["**Slump test — SCIATIC**","**Sensitivity 44–87%, specificity 23–63%** (2010 review). Sitting, hips neutral, hands behind the back → slump into lumbar and thoracic flexion with the head erect → overpressure at the shoulders → **chin to chest** with overpressure → **active knee extension** on the affected side → **passive dorsiflexion**. Stop advancing the sequence the moment symptoms increase. Positive = reproduction of neurological symptoms; **hamstring tension or T8–T9 tension is NOT a positive**"],
 ["**Straight leg raise (Lasègue) — SCIATIC / lumbosacral roots**","Supine, hip **medially rotated**, knee extended, hip flexed to ~90° if tolerated → **dorsiflexion** to add stretch (lower the leg 5° first if the posterior muscles are fully tensed) → then plantarflexion and inversion, hip adduction, more medial rotation, and **neck flexion** as sensitizers. Positive with significant back or radicular leg pain; **leg pain WITHOUT spinal symptoms → consider piriformis syndrome**"],
 ["**Prone knee bend (reverse Lasègue) — FEMORAL**","Prone, spine and hip neutral (not extended) → flex the knee to resistance or symptom reproduction → add **passive hip extension** to emphasize. Suri et al 2011: for **L2–L4 sensitivity 50%, specificity 100%**; for L3 alone **sensitivity 70%, specificity 88%**. Positive = shooting pain down the leg or anterior thigh. Some authors hold 45–60 seconds — likely **too provocative in active root compression**"]],[2400,6960]));
k.push(bullet("Context worth carrying: **90% of lumbar radiculopathy involves L4–L5 or L5–S1** (highest static and kinetic forces); herniation with root compression at **L3–L4 and above is uncommon (~5%)**, which is exactly why the prone knee bend is the femoral-side test. And a positive neurodynamic test never replaces **sensory, motor, and reflex assessment**."));

/* ─────────────── 6.9 SYNDROMES ─────────────── */
k.push(pageBreak());
k.push(banner("TOPIC 6.9","Common MSK Syndromes Leading to Impaired Nerve Function"));
k.push(spacer());
k.push(h1("Thoracic Outlet Syndrome"));
k.push(bullet("**Epidemiology**: ~**8% of the population**, **3–4× more frequent in women**, ages 20–50, mean age 30s–40s, rare in children. Anatomy behind the sex difference: less-developed musculature, greater tendency to drooping shoulders from breast tissue weight, a narrower outlet, and an anatomically lower sternum — all changing the scalene angle. **95–98% of cases affect the brachial plexus**; only 2–5% are vascular (subclavian artery or vein). **Causes**: compressive neuropathy, **faulty posture** (forward head, increased thoracic kyphosis, protracted scapulae, forward shoulders — the student posture), and **entrapment** (pectoralis minor tightness, scarring and adhesions, scalene overuse or hypertrophy from accessory breathing, elevated first rib, depressed scapula)."));
k.push(detail(["TOS type","Presentation"],[
 ["**Arterial**","Younger adults doing **vigorous overhead activity** (electricians, plumbers). Hand pain and **claudication with pallor**, cold intolerance, paresthesia; onset is often spontaneous"],
 ["**Venous**","Younger men with vigorous arm activity: **cyanosis**, heaviness, paresthesia in the fingers and hand from edema, and edema traveling up the arm"],
 ["**True neurogenic**","History of neck trauma or cervical injury: pain, paresthesia, numbness, weakness; occipital headaches; loss of fine motor skills; cold intolerance (possible Raynaud's). **Weakness is OBJECTIVE and documentable on MMT.** Symptoms present day and night, **worse during the DAY**"],
 ["**Neurogenic (disputed)**","Same history and symptom set, but **weakness is SUBJECTIVE — the patient feels weak without measurable loss** — and **nocturnal paresthesias wake the patient**, with symptoms greater at NIGHT than during the day"]],[2400,6960]));
k.push(bullet("**TOS treatment**: education about the syndrome and **postural awareness** with correction techniques · modify provoking stressors · home program · **correct abnormal breathing** (relax the upper thorax, teach diaphragmatic/abdominal breathing) · **correct scapular positioning** by strengthening the scapular stabilizers · **mobilize the first rib and thoracic spine** · **soft tissue mobilization of pec major and minor** · suboccipital release and self-stretching for restricted muscles · **nerve glides**."));
k.push(h1("Carpal Tunnel, Ulnar Entrapment, and CRPS"));
k.push(detail(["Syndrome","Presentation and management"],[
 ["**Carpal tunnel syndrome**","**The most common entrapment neuropathy in the upper extremity — 3–6% of adults, 3× more common in women.** Median nerve compromised in the tunnel → early **pain, numbness, paresthesia along the median distribution** (thumb, index, middle, and the **radial half of the ring finger**), radiating up the arm to shoulder and neck; progression brings **night pain, hand weakness, reduced fine motor coordination and grip, clumsiness, reduced wrist mobility, and thenar atrophy**. Treat: education on protecting the nerve, a **static wrist orthosis in NEUTRAL for sleeping**, protect insensate areas, modify provoking activity, **mobilize restricted carpals (grade 3–4)**, tendon gliding and **median nerve glides**, gentle multi-angle muscle setting → resistance → endurance, plus fine finger dexterity work"],
 ["**Median nerve glide sequence**","**A** wrist neutral, fingers and thumb flexed → **B** wrist neutral, fingers and thumb extended → **C** wrist and fingers extended, thumb neutral → **D** wrist, fingers, and thumb extended → **E** same plus **forearm supinated** → **F** same plus **thumb stretched into extension**"],
 ["**Ulnar entrapment**","**Cubital tunnel** at the elbow; **Guyon's canal** at the wrist (between the **hook of the hamate and the transverse carpal ligament**) — an overuse injury from handlebar pressure (**handlebar palsy**), weightlifting, heavy equipment, excessive gripping or twisting, or prolonged wrist flexion with ulnar deviation. Symptoms: **tingling in digits 4 and 5**, pain, weak grip, forearm/wrist/hand sensitivity, **atrophy of hypothenar and interossei with the thenar group SPARED**, weak finger abduction/adduction and thumb adduction, **clawing of digits 4–5**, **ulnar claw and the sign of Benediction**, fatigue with sustained activity, and loss of spherical/cylindrical power grip. Treat like CTS: education, modify the provoking activity, **avoid pressure on the base of the palm**, hand-based ulnar orthosis, and **ulnar nerve glides — wrist into extension and radial deviation, then overpressure into extension against the ring and little fingers**"],
 ["**Complex regional pain syndrome**","Formerly reflex sympathetic dystrophy. More common in females, ages 3–75 but most prevalent in the **mid-30s**; **type I occurs in 5% of traumatic injuries, with 91% of cases following surgery or trauma**. **Type I**: precipitating event sometimes present, **no single peripheral nerve involvement**, physiological change in the limb, spontaneous pain, swelling, skin temperature differences, progressive, **bone atrophy**. **Type II**: definite precipitating event, **single peripheral nerve involvement**, **burning pain, allodynia, hyperalgesia**, sometimes progressive, no bone atrophy"]],[2400,6960]));
k.push(bullet("**CRPS management — early**: relieve pain and control edema (**high-volt e-stim or TENS**; heat or ice **depending on vasomotor status**; fluidotherapy, sometimes combined with active exercise), **retrograde massage** with the limb elevated, compression sleeve or glove, **mirror therapy** (correcting sensorimotor incongruence by visualizing the unaffected limb in the affected limb's position), **graded motor imagery**, gentle joint mobilization including the **upper thoracic spine**, gentle exercise with **closed-chain loading of the affected limb**, mobilization with distraction, low-impact aerobic or aquatic exercise for total-body circulation, and **desensitization in brief bouts five times a day** — with the education to explain why it's worth doing something uncomfortable. **Chronic stage**: continued pain management, tissue-specific mobility, functional performance with compensation or assistive devices where needed, and careful monitoring of strength, endurance, and functional progress."));

/* ─────────────── SYNC + STUDY ─────────────── */
k.push(pageBreak());
k.push(banner("MODULE 6","Sync Session, Reading Map, and Glossary"));
k.push(spacer());
k.push(detail(["Sync question","Answer"],[
 ["Maximal protection phase priorities","**Protect the repair, manage pain and swelling, prevent complications** — not max strength, not aggressive stretching, not return-to-sport testing"],
 ["The PT hard stop with suspected DVT","**Avoid heat, ROM, and the compression pump — and escalate.** Never heat the calf, never deep-massage it, never load it"],
 ["A positive neurodynamic test","**Symptom reproduction + side-to-side difference + sensitizer response** — not any stretch sensation, not end-range discomfort, not tenderness to palpation"],
 ["Peripheral nerve injury management in one line","**Acute: protect → Recovery: retrain → Chronic: compensate**"],
 ["The nerve glide rule","**Gentle dosing at the symptom threshold, then re-test** — don't push into symptoms, don't hold end range for 60 seconds, and 'only when pain-free' is too conservative"],
 ["What changes between day 4 and week 10 post-op","How much **stress the tissue can handle**, how much **motion** is allowed, how much **load** is appropriate, **which exercises** make sense, and **what level of function** is realistic"]],[2600,6760]));
k.push(bullet("**Quiz 4 corrections carried into sync** (class average 89%): cross-fiber massage is the technique **NOT** used for signs of chronic inflammation of a muscle group · for stiffness and limited ROM **without pain**, the appropriate choice is **end-range joint or muscle stretching** (grade I–II distraction is for pain you don't have) · transient or intermittent pain in the **chronic** stage is best relieved by **stretching and strengthening the healing tissue**, not by heat and massage."));
k.push(spacer());
k.push(detail(["Topic","Source"],[
 ["Pre-op and surgical procedures","Preoperative Care (6.1) and Common Surgical Procedures (6.2) lectures + slides; **Ohno et al 2022** — 3-week preoperative rehabilitation on pain and daily physical activity (module folder); the **ACL rehabilitation protocol** example in Canvas"],
 ["Post-op","Post-Op Examination and Phases (6.3), Complications and Risk Reduction (6.4), Post-Op Interventions (6.5) lectures + slides; Cameron's modality decision tables"],
 ["Peripheral nerve","Impaired Nerve Function (6.6), Classification and Management (6.7), Neurodynamic Disorders (6.8), Common MSK Syndromes (6.9) lectures + slides; the **nerve glide video collection** in the module folder"],
 ["Assessment","Quiz 4 · **Case Study #2 (home exercise plan) due March 24** · Sync 7 · final exam · **lab immersion March 30 – April 1** (Modules 6 and 7 skills list is combined with the lab manual)"]],[2400,6960]));
k.push(spacer());
k.push(...glossary("Module 6 Quick-Reference Glossary",[
 ["Prehabilitation","Pre-op education + exercise → less pain, better function, greater quad strength, shorter stay"],
 ["Autograft / allograft / synthetic","Own tissue (two sites) / donor tissue (rejection, disease) / Gore-Tex or Dacron (high failure, synovitis)"],
 ["Muscle repair timing","Surgery DELAYED 48–72 h; immobilized shortened; isometrics only; no vigorous stretch for 6–8 weeks"],
 ["Tendon repair timing","Repair IMMEDIATELY (retraction); longer immobilization; early gentle setting to prevent adhesion; no heavy lifting 6–8 weeks; no vigorous stretch/resistance until 8 weeks"],
 ["Transfer vs realignment","Transfer changes line of pull AND action (retrain with biofeedback/e-stim); realignment changes line of pull only"],
 ["Microfracture","Repairs osteochondral defects <1.5 cm"],
 ["Cartilage procedure timeline","FWB by 6–8 weeks; progressive program 6 months to a year"],
 ["Osteotomy","Cut and realign bone to shift load to intact surfaces — delays joint replacement in younger patients"],
 ["Arthrodesis","Fusion when stability matters more than mobility; also a salvage after failed arthroplasty"],
 ["Maximum protection phase","Days to 6 weeks; protect, decrease pain, prevent infection/swelling/pulmonary-circulatory complications, muscle setting"],
 ["Moderate protection phase","~4–6 weeks post-op for another 4–6; entry = no pain at rest + limited pain-free motion; scar management, grade 3–4 mobs, concentric and rhythmic stabilization"],
 ["Minimal protection phase","6–12 weeks to 6 months+; full or near-full pain-free AROM and stability; functional strength"],
 ["6-week rule","No vigorous stretching or resistance on repaired muscle, tendon, or capsule for at least 6 weeks"],
 ["Wells DVT","≥3 high risk, 1–2 moderate, 0 low; every post-op patient starts with a point"],
 ["DVT contraindications","PROM/AROM, moist heat, sequential compression pump — and no mobilization before therapeutic anticoagulation"],
 ["Intraneural vs extraneural","Conducting tissue or the nerve's own connective tissue vs the nerve bed and surroundings"],
 ["Saturday night / crutch palsy","Radial nerve compression from arm-over-chair sleeping / axillary crutch leaning"],
 ["Tunnel of Guyon","Ulnar entrapment at the wrist → partial claw hand; hook of hamate and transverse carpal ligament"],
 ["Common fibular injury","Fibular neck compression → foot drop (deep branch) or eversion loss (superficial branch)"],
 ["Seddon / Sunderland","The two PNI classification systems, graded by depth of injury"],
 ["Nerve phases","Acute protect (immobilize days–3 weeks) → Recovery retrain (re-innervation, hypersensitivity) → Chronic compensate"],
 ["TENS dosing for neuropathy","Acute: ≤1 h/day at 80–120 Hz · Chronic: ≤30 min/day at 2–10 Hz"],
 ["Desensitization vibration order","Slow (~30 CPS) → wand touch → constant touch → rapid (~250 CPS), proximal to distal"],
 ["Positive neurodynamic test","Symptom reproduction + >10° side-to-side elbow extension difference + sensitizer response"],
 ["ULNT 1 / 2B / 3","Median (abduct 110°, supinate, extend) / radial (abduct 20–30°, IR, pronate, flex) / ulnar (abduct 110°, pronate, extend wrist, FLEX elbow)"],
 ["Slump vs SLR vs prone knee bend","Sciatic in sitting (Sn 44–87%, Sp 23–63%) / sciatic supine with DF sensitizer / femoral in prone (L2–L4 Sn 50%, Sp 100%)"],
 ["TOS types","Arterial (pallor, claudication) · venous (cyanosis, edema) · true (OBJECTIVE weakness, worse by day) · neurogenic (SUBJECTIVE weakness, worse at night)"],
 ["Carpal tunnel","Most common UE entrapment; 3–6% of adults, 3× women; night orthosis in NEUTRAL; median nerve glides A–F"],
 ["CRPS I vs II","No single nerve, physiological limb change, bone atrophy vs single nerve involvement, burning pain, allodynia, hyperalgesia"],
 ["Mirror therapy / graded motor imagery","Movement representation techniques correcting sensorimotor incongruence — phantom limb pain, CRPS"]]));

build(k,"/home/claude/out/TI2_Module6_PreopPostopPeripheralNerve_StudyNotes.docx");
