const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const k=[];

k.push(...cover("Musculoskeletal Practice I (DPTH 6412)","Module 5: Pelvic Floor and Hip",
 "Topic 1: Pelvic Floor Dysfunction, Examination & Treatment (Dr. Sammis + async lectures) • Topic 2: Hip Biomechanics • Topic 3: Hip Osteoarthritis • Topic 4: Hip Fracture & THA (Dr. Barrett)",
 ["Watch the lectures in your own Canvas module — these notes condense them, they don't replace them",
  "★ Two exam anchors this module: the core canister (diaphragm-abs-pelvic floor-multifidus) and the three hip angles (inclination, torsion, alpha)",
  "Everyone has a pelvic floor — screening it is entry-level; internal examination is NOT (advanced training required)"]));

/* ─────────────── TOPIC 1a: PELVIS + PELVIC FLOOR ANATOMY ─────────────── */
k.push(banner("TOPIC 1","The Pelvis as the Crossroads — Functional Anatomy Refresher"));
k.push(spacer());
k.push(h1("1. Three Jobs of the Pelvis"));
k.push(detail(["Function","What it means clinically"],[
 ["**Postural aptitude**","The pelvis is the base of the spine and dictates posture: posterior tilt flattens lumbar lordosis → ↑thoracic kyphosis → loss of cervical lordosis (and the diaphragm-to-pelvic-floor alignment changes with it); anterior tilt drives hyperlordosis + rib flare. No posture is 'bad' — the question is whether the patient is STUCK in one and whether that position correlates with their symptoms"],
 ["**Force generation + attenuation**","Functional force originates in the lumbopelvic complex (sit-to-stand, golf swing, bat swing). In gait, transverse-plane pelvic rotation is the force that RE-SUPINATES the foot for a stable push-off arch — no pelvic rotation, no timely supination. The closed osteoarticular ring structure makes the pelvis ideal for attenuating enormous ground-reaction forces"],
 ["**Load transfer**","The link between axial and appendicular skeletons — facilitated by **36 muscles, 5 ligaments, and 8 joints**, which is exactly why identifying the primary driver of pelvic dysfunction is hard"]],[2600,6760]));
k.push(h1("2. Pelvic Floor Musculature — Layers, Deep to Superficial"));
k.push(bullet("**Pelvic diaphragm** (deepest): the **levator ani** — three muscles sharing the levator ani nerve and one job (support pelvic organs, maintain urinary + fecal continence): **puborectalis** (pubis → wraps behind the rectum → back to pubis; contraction kinks the anorectal angle like a bend in a hose — eccentric lengthening straightens it for defecation), **pubococcygeus** (pubis → coccyx), **iliococcygeus** (tendinous arch + ischial spine → coccyx). Plus **coccygeus/ischiococcygeus** (ischial spine → sacrum/coccyx; the 'tail-wagging' muscle — bilateral contraction flexes the coccyx; nerve to coccygeus)."));
k.push(bullet("Moving superficially: **deep perineal pouch** (deep transverse perineal + external urethral sphincter) → **superficial perineal pouch** (superficial transverse perineal, bulbospongiosus around the vaginal opening, ischiocavernosus along the ischium — the sexual-function layer) → **external anal sphincter** (most superficial). The perineum = the diamond from coccyx to ischial tuberosities to pubic symphysis, split into the **urogenital triangle** (anterior: urethra ± vagina, or penis) and **anorectal triangle** (posterior)."));
k.push(bullet("**Two hip muscles moonlight as pelvic walls**: **piriformis** (anterior sacrum → greater trochanter; posterior-superior wall; ER + abduction; anterior rami S1-S2, intimate with the sciatic nerve) and **obturator internus** (obturator membrane → greater trochanter; anterolateral wall; nerve to obturator internus). Overload in the floor shifts work to these two — which is why an overactive pelvic floor can masquerade as **hip pain** for years, and why hip pain workups should clear the pelvic floor."));
k.push(bullet("**Blood supply**: abdominal aorta → common iliacs → **internal iliac artery** perfuses most of the pelvis (anterior + posterior divisions; terminal branches include inferior gluteal, obturator, and **internal pudendal** arteries). Palpable inguinal lymph-node clusters live here too — know what a swollen node feels like and refer when unexpected."));
k.push(h1("3. Sacral + Pelvic Motion and the Sling Systems"));
k.push(bullet("**Nutation** = sacral promontory nods anteriorly → maximal SIJ congruity, the **closed-pack, most stable** position, checked by the **sacrotuberous ligament**. **Counternutation** = promontory moves posteriorly → **loose-pack**, checked by the **long dorsal SI ligament**. Whole-pelvis tilts: posterior tilt = ASISs rise (rectus abdominis pulls the pubis up + hamstrings pull the ischial tuberosities down); anterior tilt = ASISs drop (erector spinae pull up posteriorly + iliopsoas/rectus femoris pull down anteriorly)."));
k.push(bullet("**Myers ('Anatomy Trains') stabilizing systems** — no muscle crosses only one pelvic joint, so stability is system-level: **deep longitudinal** (erector spinae + deep thoracolumbar fascia + sacrotuberous ligament + biceps femoris — posterior); **inner core** (pelvic floor + transversus abdominis + multifidus); **posterior oblique** X (glute max × contralateral latissimus through the thoracolumbar fascia); **anterior oblique** X (external obliques × contralateral adductors); **lateral** (glute med/min + contralateral adductors — frontal-plane control)."));

k.push(pageBreak());
/* ─────────────── TOPIC 1b: DYSFUNCTION ─────────────── */
k.push(banner("TOPIC 1 (cont.)","Pelvic Floor Dysfunction"));
k.push(spacer());
k.push(h1("1. The Core Canister and How It Breaks"));
k.push(bullet("**Core canister**: diaphragm on top, pelvic floor on the bottom, abdominal wall around the front and sides, multifidus/posterior chain behind. The pelvic floor supports the pelvic organs, maintains urinary + fecal continence, assists sexual function, manages intra-abdominal pressure, and co-contracts with transversus abdominis to support the lumbar spine. Dysfunction anywhere in the canister (weak abdominals, stiff ribcage limiting the diaphragm, weak back extensors) shifts load INTO the pelvic floor — the floor takes the blame for the whole system."));
k.push(compare("UNDERACTIVE pelvic floor","OVERACTIVE pelvic floor",
 ["Formerly 'hypotonic.' Muscles don't contract well enough to support the organs → stress incontinence, prolapse, low-tone exam findings. Treatment direction: activate + strengthen + coordinate."],
 ["Formerly 'hypertonic.' Muscles contract all the time and can't relax or lengthen — the dimmer switch stuck on full bright. Drives pelvic pain, dyspareunia, constipation, urgency — and referred HIP pain. Treatment: down-regulate + lengthen FIRST (Kegels make this worse). ~98% of Dr. Sammis's clinic is hypertonic."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(h1("2. The Manifestations to Recognize"));
k.push(detail(["Category","Types"],[
 ["**Incontinence**","**Stress** (leak with ↑intra-abdominal pressure: cough, sneeze, jump, lift) · **Urge** (key-in-the-door, running water — sudden urgency with loss of control; distinguish from plain ↑frequency) · **Mixed** (both) · **Athletic** (leakage during sport, increasingly recognized in young pre-pregnancy female athletes — gymnastics, soccer, volleyball) · **Postural** (on transitions: lying→sit, sit→stand) · **Coital** (typically orgasmic phase) · **Anal** (feces or gas)"],
 ["**Pelvic organ prolapse**","Descent of an organ toward/through the vaginal orifice, graded by degree: **cystocele** (bladder → anterior wall) · **rectocele** (rectum → posterior wall) · **uterine prolapse** · **enterocele** (small intestine) · **urethrocele** · **vaginal vault prolapse** (post-hysterectomy). Common mechanism: poor pressure management + muscle discoordination sending pressure DOWN during transitional movements/loading"],
 ["**Pelvic pain syndromes**","**Pudendal neuralgia** (nerve compression) · **dyspareunia** (pain with penetration — penile, digital, or even tampon/menstrual-cup insertion) · **vaginismus** (involuntary protective tightening blocking entry) · **vulvodynia** · plus abdominal, low back, SI, hip, and groin pain referred from the floor"],
 ["**Bowel dysfunction**","**Constipation** (slow transit → harder stool → straining; feeds prolapse and urinary symptoms) · **defecatory disorders** (discoordinated release; can follow perineal laceration in childbirth affecting the anal sphincters)"]],[2400,6960]));
k.push(h1("3. Who Needs This? Everyone."));
k.push(bullet("Not just postpartum patients: women AND men of all ages, athletes, children, anyone with **persistent low back / hip / pelvic girdle pain**, neuromotor-control dysfunction, spinal cord injury, or post-op abdominopelvic/hip/spine surgery. Dr. Sammis's caseload is **60% male**, mostly athletes. The public-health case: chronic problems tied to pelvic floor dysfunction are projected to **increase >50% over the next 30 years**, and patients who quit exercise over leakage or pain cascade into inactivity and chronic disease. Screening is a professional duty, taboo or not."));

k.push(pageBreak());
/* ─────────────── TOPIC 1c: EXAMINATION ─────────────── */
k.push(banner("TOPIC 1 (cont.)","Pelvic Floor Examination — the Entry-Level (External) Toolkit"));
k.push(spacer());
k.push(h1("1. Subjective Screening"));
k.push(bullet("Ask every low back / hip / pelvic girdle patient: prior pelvic or coccyx injuries, motor vehicle accidents, abdominopelvic/gynecologic/spinal surgeries, pregnancy + birth history (vaginal vs cesarean, injuries), aggravators/easers (your usual SINSS), whether pain fluctuates with **menstruation**, and screening questions on **bladder, bowel, and sexual function**. Open-source tools make this painless: the **AAOMPT Pelvic Health Screening Tool** slots into intake paperwork — a single checked response in sections 1-2 flags possible pelvic floor involvement. Outcome measures: **Pelvic Floor Impact Questionnaire (PFIQ)**, **Pelvic Floor Distress Inventory (PFDI** — adds level-of-bother, like a pain-catastrophizing lens**)**, **ICIQ male lower urinary tract symptoms** for men, and the always-flexible Patient-Specific Functional Scale."));
k.push(bullet("**Bowel + bladder diary** (~3 days): fluid type + volume, void times + amounts, urge vs 'just in case' voiding, leaks + what triggered them + how much, bowel vs bladder, stool consistency. Patients spot their own trends before you say a word. Norms to anchor against: voiding **every 2-3 hours**, and under age 65 (non-pregnant) you shouldn't need to get up at night."));
k.push(h1("2. Objective Screening — No Internal Exam Required"));
k.push(detail(["Item","What you're looking for"],[
 ["**Posture + functional movement**","Pelvic position, ribcage stacked over pelvis (or flared/tucked), spinal curves, chain findings (pronation, ER). Then load it: squat, hip hinge, single-leg stance, step up/down, gait, and the SPECIFIC task that provokes symptoms (which lift? carrying the toddler on one hip?)"],
 ["**Breathing assessment**","Resting ribcage position + **infrasternal angle** (~90°; widens to 120-130° in pregnancy). Then 'take a deep breath': 360° lateral-costal diaphragmatic expansion vs **apical** (accessory muscles — often pairs with tension headaches), **belly-only**, **paradoxical** (everything sucks IN on inhale), or asymmetric. Watch for breath-holding during loaded tasks — a pressure-management tell that links directly to leaking"],
 ["**Abdominal wall**","Tissue mobility + resting tone (a ropey, tender, hypertonic wall is dysfunction, not fitness), scar mobility after cesarean/abdominal surgery, coordination strategy (oblique/psoas/QL domination vs clean deep-core recruitment)"],
 ["**Active straight leg raise (ASLR)**","Rate the effort of lifting one leg supine; re-test with therapist compression of the pelvis. Markedly easier → the force-closure/stabilization system (TrA and friends) needs strengthening"],
 ["**Diastasis rectus abdominis (DRA)**","Two fingers perpendicular to the linea alba at, above, and below the umbilicus; patient lifts head. **>2 finger-widths of inter-rectus distance is abnormal — but DEPTH/TENSION matters more than width** (good tension under the fingers = better prognosis). Note coning/doming ('bread-loafing') and juddering; also test in function (pull-up, loaded squat) where symptoms actually occur"],
 ["**Coccygeal movement test**","Sitting/sidelying/standing: heel of hand on sacrum, third digit along the coccyx. Pelvic floor contraction should pull the coccyx anteriorly (a lift); bearing down / diaphragmatic breath should move it slightly posteriorly (a lengthening). Paradoxical or absent motion — or pain (coccydynia) — flags dysfunction"],
 ["**External pelvic floor assessment**","Sidelying preferred (easy landmarks, less vulnerable). Palpate medial to the ischial tuberosity toward the anorectal canal — tuberosity-biased ≈ obturator internus, more midline between anus and tuberosity ≈ levator ani. Assess: tone (hyper vs hypo), pain, contract-on-cue (hand pushed out), relax (hand sinks in), **cough** (should get a reflexive squeeze-and-LIFT — absence explains stress leaks), **bear down** (should soften/descend)"]],[2700,6660]));
k.push(tnote("Consent is not a formality here: explain intent, expected information, and exactly where you'll touch, using clear professional language; respect refusal without pushing. Sexual trauma history is common in patients with pelvic symptoms — approach the region accordingly. And remember the scope line: external screening = entry-level; INTERNAL examination = advanced post-professional training."));

k.push(pageBreak());
/* ─────────────── TOPIC 1d: TREATMENT ─────────────── */
k.push(banner("TOPIC 1 (cont.)","Pelvic Floor Treatment"));
k.push(spacer());
k.push(h1("1. Lifestyle Interventions (Where You Can Win Big)"));
k.push(detail(["Lever","The teaching"],[
 ["**Hydration**","Leakers often restrict water — which BACKFIRES: concentrated urine is noxious to the bladder wall and amplifies urgency signals. So do caffeine and certain sweeteners. Often the first fix is drinking MORE water"],
 ["**Bathroom habits**","Normal = every 2-3 h; no overnight voids under 65 (non-pregnant). Teach **urge-suppression** stalling strategies to retrain bladder filling; kill the 'just in case' void — it trains urgency and frequency"],
 ["**Toilet mechanics**","Squatty-potty/stool posture: hips into deep flexion eccentrically elongates **puborectalis**, opening the anorectal angle for easy defecation"],
 ["**Stool consistency (Bristol scale)**","Target types 3-4. Types 1-2 (hard) → more water + INsoluble fiber to speed colonic transit. Types 6-7 (loose → fecal-incontinence and dehydration risk) → water-SOLUBLE fiber to hold water and bulk the stool"],
 ["**Stress management**","Fight-or-flight clenches the jaw — and the pelvic floor (notice it in a scary movie). For the overactive floor: nervous-system down-regulation, diaphragmatic breathing, meditation, sleep, daily movement (which also fights constipation)"]],[2700,6660]));
k.push(h1("2. Neuromotor Retraining — Same Ladder as the Lumbar Spine"));
k.push(bullet("**Activation/coordination**: start at the TOP of the canister — restore a 360° diaphragmatic breath (tactile hands around the lower ribs). The diaphragm-pelvic floor connection is the treatment: as the diaphragm descends, the floor reciprocally softens and bulges down — free lengthening for the overactive floor. Add floor-specific work: sitting on a ball, let the floor melt down into the surface on the inhale, then **squeeze AND LIFT toward the head** (a proper Kegel is squeeze + lift; relaxation should feel like lowering/bulging toward the sit bones). Overactive floors can also get **ischemic compression** — tennis ball under the pelvic floor (off bony prominences) + diaphragmatic breathing. Then integrate: exhale → ribs draw down-and-in → pelvic floor up-and-in → TrA brace."));
k.push(bullet("**Acquisition**: keep the lumbopelvic brace while dissociating limbs — LE and UE movement without losing the canister; hip dissociating from trunk. Then reintroduce articulated spinal motion so the obliques learn to control rotation. **Assimilation**: task-specific progressive overload back to the exact activities that leaked or hurt — low-level control first, then load, then the sport/lift/carry itself."));
k.push(tip("Direction matters more than effort: an OVERACTIVE floor gets lengthening, breathing, and down-regulation before any strengthening — prescribing Kegels to a hypertonic floor is pouring gas on the fire. Match the treatment to the exam, not to the word 'weak.'"));
k.push(h1("3. Sync Session — Two Pattern-Recognition Cases"));
k.push(compare("LOGAN — 34F PT, 2 months post 2nd cesarean","ROGER — 35M program manager, avid cyclist",
 ["R low back/buttock pain (sit-to-stand, stairs), leaking when lifting her toddler or sneezing, heaviness with prolonged standing (relief lying with legs up). Exam: R Trendelenburg, +ASLR, +thigh thrust/distraction/compression, painful hypomobile cesarean scar, wide infrasternal angle + anterior rib elevation, DRA 3 finger-widths but TAUT, obturator internus tenderness, floor descends with cough WITHOUT TrA co-contraction. Drivers: SIJ + underactive/discoordinated floor + scar. Plan: scar mobilization, thoracic mobility, then the activation→acquisition→assimilation ladder for diaphragm-abs-floor."],
 ["Progressive sharp groin + genital pain (posterior scrotum/perineum, saddle tingling → sharp), worse with sitting, cycling, stress; better standing/stretching/meditating. Straining with bowel movements, erectile dysfunction, only 30-50 oz water/day. Exam: Laslett cluster NEGATIVE, restricted hips + lumbopelvic mobility, severe tenderness of urogenital muscles/levator ani/obturator internus reproducing his pain, pain near the pudendal canal, CANNOT volitionally contract OR relax. Driver: overactive floor + pudendal irritation. Plan: down-regulation + breath training, external (and referred-out internal) soft-tissue work, hip/lumbopelvic mobility, hydration; 3/10 by visit 3, then progressive loading."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(tnote("The referral question from the breakout rooms: both cases benefit from an internal-skill-set pelvic PT — but notice how much of each plan (education, breathing, hips, scar, load management, hydration) is squarely inside ORTHOPEDIC entry-level scope. Screen, start, refer, co-manage."));

k.push(pageBreak());
/* ─────────────── TOPIC 2: HIP BIOMECHANICS ─────────────── */
k.push(banner("TOPIC 2","Clinical Biomechanics of the Hip"));
k.push(spacer());
k.push(h1("1. Joint Architecture"));
k.push(bullet("Ball-and-socket, 3 degrees of freedom, convex femoral head on concave acetabulum (roll and slide OPPOSITE). **Loose-pack**: ~35° flexion + 35° abduction + slight ER — the position of comfort in a painful/effused hip. **Closed-pack**: maximal extension + IR + abduction. The acetabulum (all three os coxae bones) is a true hemisphere facing lateral-inferior-anterior; the femoral head is ~2/3 of a sphere, so it is NOT fully contained — cartilage is thickest superiorly on both sides where weight-bearing contact forces peak."));
k.push(bullet("**Labrum** — the stability workhorse: fibrocartilage ring adding **~20% articular surface area** (distributes contact stress) and **~20% socket depth**, and sealing synovial fluid in for lubrication, nutrition, and load-sharing fluid pressurization. Innervation concentrates **anterior + superior** (tears there hurt); only the outer third is vascularized (peripheral tears can heal). **Ligamentum teres** is a conduit, not a stabilizer: it carries the **obturator artery** to the femoral head via the fovea — disruption → avascular necrosis → usually THA. The three strong capsular ligaments **wind up in extension**, adding weight-bearing stability and limiting hyperextension; capsular frenula allow full frontal-plane motion."));
k.push(h1("2. The Three Angles ★"));
k.push(detail(["Angle","Clinical story"],[
 ["**Inclination (neck-shaft, frontal plane)**","~150° newborn → **~125° adult**, still decreasing with age; smaller in females (wider pelvis). **>125° = coxa valga** → shaft angles toward midline distally → **genu VARUM**. **<125° = coxa vara** → **genu VALGUM** (knock knees). Frontal-plane terms only — no rotation implied"],
 ["**Torsion (transverse plane)**","Head-neck axis vs condylar axis; adult average **~12° anteversion**. **Excess anteversion (>12°)** → limb functions INTERNALLY rotated (in-toed patella in stance, IR ROM ≫ ER). **Retroversion (<12°)** → externally rotated limb. In adults torsion (structure) and version (position) are used interchangeably; in pediatrics they diverge. Spot it in gait: patella faces forward in swing, dives inward at loading"],
 ["**Alpha angle (transverse plane)**","Center of head → point where the head-neck contour leaves the circle of the head. **>55° (some sources 45°) = cam-type deformity** → femoroacetabular impingement, labral tears anterosuperiorly; impingement position = **flexion + IR + adduction**"]],[2700,6660]));
k.push(bullet("**The femoral neck is a cantilever**: it buys the abductors a long moment arm (mechanical advantage) at the price of bending stress — tension across the SUPERIOR neck, and a smaller cross-section than head or shaft, which is why necks fracture. Strong hip abductors add compression that cancels part of the bending tension — one more argument for strength as fracture prevention in aging."));
k.push(bullet("**Closed chain = pelvis on femur**: anterior pelvic tilt = relative hip FLEXION; posterior tilt = relative extension. Left lateral tilt (right hip-hike) = right hip adduction + left hip abduction. Pelvic rotation LEFT = left hip IR + right hip ER. Stand up and act these out — they show up on every gait exam."));

k.push(pageBreak());
/* ─────────────── TOPIC 3: HIP OA ─────────────── */
k.push(banner("TOPIC 3","Hip Osteoarthritis"));
k.push(spacer());
k.push(h1("1. Recognizing It"));
k.push(bullet("Radiographic OA in up to **27% of adults** (males show more imaging OA; **females more often SYMPTOMATIC**); symptomatic hip OA ≈ 3% of US adults ≥30, rising 2-10× from ages 30-65. Diagnosed on plain radiograph (joint-space narrowing — the 'bone on bone' the patient quotes); **no MRI needed**. Risk accelerants: acetabular retroversion, developmental dysplasia, **FAI** — which is how a 27-year-old ends up with bilateral THAs. History: groin/medial-thigh ache after activity, gradual worsening, **morning stiffness <1 hour** ('once I get grease on the wheels'), stiffness the day AFTER prolonged weight-bearing, limp out of a chair, pain with low chairs and car transfers."));
k.push(infoBox("2017 CPG key clinical findings (the more present, the likelier hip OA)",["Moderate ANTERIOR or LATERAL hip pain with weight-bearing • morning stiffness <1 h • **hip IR <24°** • IR + flexion ≥15° less than the non-painful side • pain on PASSIVE IR • no history/findings inconsistent with OA"],C.gold,C.lightGold));
k.push(bullet("Strength findings (vs matched controls): abduction **-31%**, adduction -25%, flexion and extension also down — with **unchanged muscle cross-sectional area**, pointing at fatty infiltration/quality, not size. Poor-conservative-outcome predictors worth an honest surgical conversation: total rotation ROM **<42°** and symptoms **>36 months**. Measure function with HOOS (OA-specific), LEFS, or Harris Hip Score plus at least one performance test matched to the patient (4-square, step test, timed single-leg stance, 30-s sit-to-stand, TUG, 6-min walk)."));
k.push(h1("2. Treating It (Conservative First — 'You Can Always Replace a Joint')"));
k.push(bullet("**Manual therapy (Grade A)** — patients with OA love the space it creates: **long-axis distraction HVLA thrust** (flexion + ER, lean back, thrust through tibia/fibula — or through the femur if the knee complains), **inferior glide with mobilization belt** (± mobilization-with-movement into flexion), **lateral traction** (belt pulls out, hands stabilize ASIS + femur — helps flexion, ER, adduction), flexion-IR MWM (glide on, patient actively IRs — never push into the pinch), AP mobs over the crossed leg for the posterior capsule, and prone/supine **PA glides** into extension (± ER progression) for terminal-stance gait."));
k.push(bullet("**Exercise (Grade A)**: flexibility + strengthening + endurance, **1-5×/week for 6-12 weeks** (mild-moderate OA) — strengthen abductors, ERs, extensors; stretch capsule, hip flexors, and ERs. Function, gait, and balance training; correct assistive-device fitting to extend symptom-free walking distance. **Education combined with exercise (B)**: weight-bearing modification (pool > pavement when flared), weight-loss referral (C) — any extra load is load. Ultrasound (B) only as a short-term adjunct. A Disneyland flare is not a surgical indication: let the joint calm down, mobilize, re-assess — 'let the joint speak to us.' Delay costs nothing: outcomes are not better for operating sooner, so patient autonomy leads the timing."));
k.push(linkBox("Required reading",[["Cibulka MT, Bloom NJ, Enseki KR, et al. Hip Pain and Mobility Deficits — Hip Osteoarthritis: Revision 2017. J Orthop Sports Phys Ther 2017;47(6):A1-A37","https://www.jospt.org/doi/10.2519/jospt.2017.0301"," — the CPG behind the criteria box and the intervention grades (full text free)"]]));

k.push(pageBreak());
/* ─────────────── TOPIC 4: FRACTURE + THA ─────────────── */
k.push(banner("TOPIC 4","Hip Fracture and Total Hip Arthroplasty"));
k.push(spacer());
k.push(h1("1. Hip Fracture — the Sobering Numbers"));
k.push(bullet("**90% of hip fractures occur in patients >65 from a ground-level fall** ('frailty fractures'). Mortality: up to **8× higher risk of death within 3 months**; 1-year mortality **21.9% (F) / 32.5% (M)**; one study found 15× first-month excess mortality NOT fully explained by pre-fracture health — the fracture itself carries risk. Top morbidities: DVT, heterotopic ossification, ulcers, nonunion, infection, mechanical failure, PE, dislocation. You will treat these patients in every setting except pediatrics."));
k.push(bullet("**Occult-fracture screens for outpatient**: **patellar-pubic percussion test** — stethoscope on the pubic symphysis, tap each patella; a duller/quieter note on one side = sound not conducting through intact bone. **Sign of the buttock** — passive SLR to end range, then flex the knee: if hip flexion does NOT increase once the hamstrings are slack, suspect a space-occupying lesion (fracture, tumor, abscess) and refer."));
k.push(detail(["Fracture pattern","Management logic"],[
 ["**Femoral neck types 1-2** (incomplete; complete non-displaced)","Percutaneous pinning (ORIF). Intracapsular location"],
 ["**Femoral neck types 3-4** (complete, <50% / >50% displaced)","Displacement threatens the femoral-head blood supply → osteonecrosis + nonunion risk → often **hemiarthroplasty** (or THA if pre-existing degenerative disease — skip rehabbing two surgeries). Younger patients: attempt head-sparing ORIF"],
 ["**Intertrochanteric types 1-2** (superolateral / inferolateral from the lesser trochanter)","Extracapsular (better blood supply) — typically ORIF with screws/plates"]],[3200,6160]));
k.push(bullet("**Fracture CPG**: report outcome measure + physical impairment measures (hip extensor/abductor strength, pain) + a performance measure (gait speed, TUG, 6-min walk, 5×sit-to-stand). Inpatient: multidisciplinary care with **early mobilization — out of bed and ambulating as soon as possible, then at least daily**; high-frequency in-hospital PT + HEP; NMES for quads if they can't exercise otherwise. Post-acute: if strength/balance/function deficits persist at **8-16 weeks**, provide MORE therapy or community strengthening — and always screen + treat **fall risk**, or the next fracture is scheduled."));
k.push(h1("2. THA — Surgery You Should Be Able to Picture"));
k.push(bullet("Most common adult surgical hip procedure. Indications: OA/RA (primary), avascular necrosis, fracture, failed reconstruction, infection, tumor, dysplasia. Bearing surfaces: metal-on-poly, ceramic-on-poly, ceramic-on-ceramic, (historical) metal-on-metal. **Approaches**: **direct anterior** (supine; sartorius-TFL interval; spares the abductors), **lateral** (lateral decubitus; SPLITS gluteus medius), **posterior** (lateral decubitus; incises glute max fascia, tags + detaches piriformis and short external rotators, protects the nearby **sciatic nerve**; dislocates the head via flexion + IR). Pre-op PT when you get it: expectation-setting (the single strongest predictor of satisfaction in some studies), transfer/device training, ADL modification, preserve ROM + strength without flaring."));
k.push(compare("POSTERIOR-approach precautions","ANTERIOR-approach precautions",
 ["No hip flexion >90° • no adduction across midline • no rotation — especially INTERNAL. The classic trio to memorize; violation position = flexion-adduction-IR (exactly how the surgeon dislocated it on the table)."],
 ["Protect the anterior capsule: no hip EXTENSION • no EXTERNAL rotation • don't cross the legs • sidelying on the SURGICAL side (or pillow between knees) so the top leg can't adduct-and-drop into the danger zone."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(bullet("**The precaution literature is dissolving**: 2015 — cutting posterior precautions from 6 to 4 weeks: no added dislocations; minimal-precaution cohorts: zero vs one dislocation; 2020 — relaxed precautions safe even controlling for femoral head size; 2023 — 10-year review of 2,000+ THAs recommends NO precautions (technique matters more). Practical rule: 'relaxed' means different things per study (shorter duration OR mid-range-only motion), so **ask each surgeon what THEIR precautions are — and assume precautions exist until told otherwise**."));
k.push(h1("3. Post-Op Plan, Red Flags, and a Full Case"));
k.push(bullet("Day 0-1 mobilization (transfers + ambulation within hours where practiced; Medicare/high-risk patients stay inpatient). Progression: walker → (cane) → full weight-bearing; ROM returns fast — expect **110-120° flexion and the ~160° combined flexion-abduction-ER needed for shoes and socks by ~6 weeks** (hips are far easier than knees). Early: bed exercises, transfers, gait, stairs/car. Intermediate (at full WB): balance/proprioception, strength, pool once the incision is healed (≥6 weeks). Late: LE endurance + sport-specific work (resisted golf swings). Discharge at prior level of function even with minor discomfort — with an HEP."));
k.push(detail(["Red flag","Findings"],[
 ["**Infection**","Fever >100°, shaking chills, spreading redness/tenderness/swelling, NEW drainage from a previously dry wound, pain rising with activity AND rest — inspect the scar at every evaluation"],
 ["**DVT (Wells)**","One point each: active cancer, paralysis/immobilization, bed rest >3 d or major surgery <4 wk (EVERY post-THA patient starts with 1), deep-vein-distribution tenderness, whole-leg swelling, calf >3 cm vs contralateral, **pitting edema**, collateral superficial veins, prior DVT; **-2** if an alternative diagnosis is at least as likely. **≥2 = likely** → refer. Expect (and accept) false positives — the catastrophic error is the false negative. Document a Wells on every post-op lower-extremity patient"],
 ["**PE (Wells)**","DVT signs, PE most-likely diagnosis, HR >100, immobilization/surgery <4 wk, prior DVT/PE, hemoptysis, active cancer — DVT's escape to the lungs; emergency"],
 ["**Metallosis**","Case: 67F, bilateral THAs 7-9 yrs prior, referred for 'back pain,' plateaued at 6 weeks → in-house musculoskeletal ultrasound found a hip soft-tissue mass → MRI + labs: cobalt poisoning → revision. Moral: when progress defies the expected trajectory, image or refer — soft-tissue masses hide in larger body habitus"]],[2500,6860]));
k.push(tnote("The threaded case: 58M, 4 wks post anterior-approach cementless THA for OA, one-story home + 4 entry steps with rails, goals = golf + walking. Eval: incision clean, Wells negative, PROM 90/8/23° (flex/ext/ER) vs 115/17/41° contralateral, MMT DEFERRED (pain + ROM limits make max testing uninformative — test function instead), Harris Hip 62, precautions = avoid forceful extension + ER. Plan 1×/wk × 2, then 2-3×/wk × 8 after full WB. Ten weeks later: golfing (2/10 after), 15° extension, 39° ER, glutes 5/5, one-mile walks ×3/wk, Harris Hip 98 — discharged WITH residual discomfort and an HEP, because prior level of function, not zero pain, is the bar."));

k.push(pageBreak());
/* ─────────────── STUDY ─────────────── */
k.push(banner("MODULE 5","Reading Map and Glossary"));
k.push(spacer());
k.push(detail(["Topic","Source"],[
 ["Pelvic floor","Pelvic Floor Dysfunction / Examination / Treatment lectures + Dr. Sammis's orthopedic-setting evaluation lecture; Pelvic Anatomy parts 1-3 + musculature handout (anatomy refresher, module folder)"],
 ["Screening tools","AAOMPT Pelvic Health Screening Tool (open source) · PFIQ · PFDI · ICIQ-MLUTS · bowel/bladder diary template"],
 ["Hip","Clinical Biomechanics of the Hip · Hip Osteoarthritis · Hip Fracture & THA parts 1-3 (Dr. Barrett) · 2017 Hip OA CPG (JOSPT link above)"],
 ["Assessment","Quiz 5 · Sync 5 cases (Logan + Roger) · lab immersion: ASLR, DRA, coccygeal motion, external pelvic floor assessment, hip mobilizations"]],[2600,6760]));
k.push(spacer());
k.push(...glossary("Module 5 Quick-Reference Glossary",[
 ["Core canister","Diaphragm (top) + abdominals (front/sides) + pelvic floor (bottom) + multifidus (back) — pressure + stability system"],
 ["Levator ani","Puborectalis + pubococcygeus + iliococcygeus; levator ani nerve; support + continence"],
 ["Puborectalis / anorectal angle","The 'kink in the hose' — contraction maintains continence, eccentric lengthening allows defecation"],
 ["Nutation / counternutation","Sacral promontory anterior = closed-pack (sacrotuberous lig.) / posterior = loose-pack (long dorsal SI lig.)"],
 ["Underactive vs overactive floor","Can't contract enough (leaks, prolapse) vs can't relax (pain, urgency) — the dimmer switch"],
 ["Stress vs urge incontinence","Leak with ↑intra-abdominal pressure vs key-in-the-door urgency loss"],
 ["Pelvic organ prolapse","Cystocele, rectocele, uterine, enterocele, urethrocele, vault — graded organ descent"],
 ["Infrasternal angle","Rib angle at the xiphoid, ~90° (120-130° in pregnancy) — diaphragm-recruitment clue"],
 ["DRA","Diastasis rectus abdominis: >2 finger-widths abnormal, but tension/depth beats width for prognosis"],
 ["ASLR test","Leg lift ± pelvic compression; easier with compression = train force closure (TrA)"],
 ["Kegel","Pelvic floor contraction = squeeze AND lift toward the head; relaxation = lowering/bulging down"],
 ["Bristol 3-4","Target stool types; 1-2 → water + insoluble fiber, 6-7 → soluble fiber"],
 ["Loose vs closed pack (hip)","35° flexion + abduction + slight ER vs max extension + IR + abduction"],
 ["Angle of inclination","Neck-shaft ~125°; coxa valga → genu varum, coxa vara → genu valgum"],
 ["Angle of torsion","~12° anteversion; excess → IR-biased limb, retroversion → ER-biased"],
 ["Alpha angle","> 55° = cam deformity → FAI, anterosuperior labral tears"],
 ["Hip OA CPG criteria","Anterior/lateral WB pain, stiffness <1 h, IR <24°, IR+flexion 15° deficit, pain on passive IR"],
 ["Patellar-pubic percussion / sign of the buttock","Occult-fracture screens: asymmetric bone conduction / no extra flexion with knee bent"],
 ["Posterior THA precautions","No flexion >90°, no adduction past midline, no (internal) rotation"],
 ["Anterior THA precautions","No extension, no ER, no leg crossing — protect the anterior capsule"],
 ["Wells DVT score","≥2 = likely; every recent post-op patient starts with a point — document it"],
 ["Metallosis","Metal-on-metal wear debris (cobalt) → soft-tissue mass; suspect when recovery defies trajectory"]]));

build(k,"/home/claude/out/Module5_PelvicFloorAndHip_StudyNotes.docx");
