const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const k=[];

k.push(...cover("Musculoskeletal Practice I (DPTH 6412)","Module 6: FAI, Hip Arthroscopy, and the Hip Across the Lifespan",
 "Topic 1: FAI, Labral Tears & Microinstability • Topic 2: Rehab After Hip Arthroscopy • Topic 3: Extra-Articular Hip Conditions • Topic 4: Pediatric Hip Disorders • Lectures by Dr. Barrett + Dr. Boucher",
 ["Watch the lectures in your own Canvas module — these notes condense them, they don't replace them",
  "★ The exam logic of this module: screen the lumbar spine → intra- vs extra-articular → then classify (FAIS, hypermobility, hypomobility) — every case runs that gauntlet",
  "Assignment this module: Patient Simulation #2"]));

/* ─────────────── TOPIC 1a: FAI ─────────────── */
k.push(banner("TOPIC 1","Femoroacetabular Impingement, Labral Tears, and Microinstability"));
k.push(spacer());
k.push(h1("1. The Morphologies"));
k.push(detail(["Type","Story"],[
 ["**Cam**","Bony overgrowth at the femoral head-neck junction (loss of sphericity/offset — the alpha angle from Module 5). Abnormal contact in **flexion + IR + adduction** → shear + compression on the ANTEROSUPERIOR labrum and chondrolabral junction → cartilage delamination first (labrum usually stays attached). Classic host: **young athletic males**. Exam tells: passive flexion drifts into ER as the bone collides; limited squat depth that IMPROVES with ER"],
 ["**Pincer**","Acetabular rim overgrowth/overcoverage (focal retroversion, coxa profunda, or extreme protrusio acetabuli). Rim abuts the neck in flexion → labral bruising, hypertrophy, ossification; less cartilage damage — but deep flexion can lever the head posteriorly (**contrecoup** posteroinferior chondral lesions). Classic host: **middle-aged athletic females**"],
 ["**Mixed**","Cam + pincer together — the combination most likely to be SYMPTOMATIC, and common in patients who actually present to PT"]],[2200,7160]));
k.push(bullet("**Morphology ≠ syndrome**: the Sync 6 paper (Feb 2021) found cam morphology in **63% of pain-free** football players' hips vs 71% of symptomatic — size and prevalence of bony shape didn't separate the painful from the painless. FAI *syndrome* = morphology + symptoms + signs. You treat the person, not the radiograph."));
k.push(h1("2. Labral Tears"));
k.push(bullet("The labrum enhances stability (suction seal), spreads articular load, and supplies proprioception — the hip's version of the meniscus. Tears cluster **anterosuperior/posterosuperior**, observed in up to **96% of older individuals**, and **47% have no specific inciting event** — degenerative wrinkles on the inside, like meniscus tears. Clicking is common; catching/locking = advanced. Tears rarely occur in isolation (usual company: FAI, microinstability, dysplasia, chondral lesions) — the isolated ones are traumatic (the Cirque du Soleil synchronized swimmer who slipped backstage and subluxed her hip, not her flexibility)."));
k.push(h1("3. Microinstability"));
k.push(bullet("Emerging entity in young athletic hips: **capsuloligamentous laxity + symptoms** (pain ± apprehension) — distinguish from plain hypermobility (extra motion WITHOUT symptoms). Usual mechanism: repetitive microtrauma insufficiency of the **anterior capsule/iliofemoral ligament** → subtle rotational instability. Cluster to diagnose: C-sign groin/deep pain, trouble with **loaded ER + extension** activities, abductor/rotator/lumbopelvic weakness, **ER >60° suggests laxity**, guarding at end-range ER/extension, and a chronically overworked (short) iliopsoas that's been moonlighting as the anterior stabilizer."));
k.push(h1("4. Examination Flow ★"));
k.push(bullet("**Step 1 — screen the lumbar spine + SIJ** (AROM with provocation, spring testing/PAs, SIJ cluster). **Step 2 — intra- vs extra-articular**: if FABER, FADIR, and IR-with-overpressure ALL fail to reproduce symptoms, think extra-articular. **Step 3 — classify** the intra-articular patient: FAIS, hypermobility, or hypomobility. Key impairment set for FAIS: pain at end ranges (flexion/adduction/IR), aggravation with repetitive or prolonged flexion (squats, long car rides — the **C-sign** patient cupping the hip above the trochanter), short iliopsoas/rectus, weak abductors + rotators + lumbopelvic muscles, poor single-leg control (**valgus collapse**, pelvic drop). Hip flexion-IR at 90° **<20° IR raises FAI risk**; symptomatic FAI hips also show **less posterior pelvic tilt during flexion** — assess the pelvis, not just the femur. Movement screens: lateral step-down, **single-leg squat (biomechanical differences are exaggerated vs double-leg)**, star excursion. Outcome measure: **iHOT-33** (young active patients; MIC ≈ 10 points)."));
k.push(detail(["Special test","Notes"],[
 ["**Hip scour**","End-range flexion, two arcs (IR-adduction ↔ ER-abduction), then repeat with axial compression. Provocative — a screen to rule OUT hip pathology; be gentle"],
 ["**Log roll**","Passive ER-IR rolling in supine — highly SPECIFIC for intra-articular tissue (moves the joint, spares extra-articular): negative in many FAI patients, but a positive is meaningful"],
 ["**FADIR (impingement test)**","Flexion-adduction-IR at 90° then at maximal flexion — positive = reproduction of groin pain"],
 ["**FABER**","Flexion-abduction-ER, stabilize opposite ASIS, press through the femur; measure knee-to-table (inclinometer or tape). Normal ≈ **20 cm** lateral joint line to table"],
 ["**Assisted (core-assisted) FABER**","From FABER position patient ACTIVELY pulls the knee toward the table: normal gains ≥4 cm (to ≈16 cm); a 'stuck' hip that gains nothing = bony infill"],
 ["**AB-HEER**","Sidelying: abduct 30-45°, extend, ER + anterior force on the greater trochanter. Sn 80.6 / Sp 89.4 — the best of the instability trio"],
 ["**HEER (anterior apprehension)**","Supine, leg over the table edge, hyperextension + ER. Sn 71 / Sp 85.1"],
 ["**Prone instability test**","Prone, knee flexed 90° as an ER lever + downward trochanter force. Sn 33.9 / **Sp 97.9** — good for ruling IN. Any positive test predicted instability in 86-90%, but negatives do NOT rule it out — use the cluster"]],[2700,6660]));

k.push(pageBreak());
/* ─────────────── TOPIC 1b: CONSERVATIVE ─────────────── */
k.push(banner("TOPIC 1 (cont.)","Conservative Management — Try It First (≥6 Weeks)"));
k.push(spacer());
k.push(compare("FAIS / hypomobility","Microinstability / hypermobility",
 ["You can't shave bone with exercise — the goals are arthrokinematics, capacity, and load management: **posterior + inferior hip mobilizations** (+ distraction — they feel great), pain-free ROM, strengthening of hip abductors/rotators + lumbopelvic muscles, neuromuscular control to compensate for the morphology. **Activity modification**: limit squat DEPTH (stop before the bony block), limit incline/stair running, adjust equipment and sport-specific patterns (a golf/baseball swing demands full IR somewhere — study THEIR movement). Progress to weight-bearing combined-plane work: single-leg external-rotation drills moving pelvis-on-femur, trunk-on-pelvis rotation with med-ball throws, step-downs, manual perturbations. Everything pain-free — no extra joint irritation."],
 ["Protect the passive stabilizers, build the active ones: **closed-chain** strengthening, stabilization, and proprioception in NON-apprehensive patterns (closed chain stimulates mechanoreceptors + co-contraction); balance/perturbation training for hip + lumbopelvic coordination; postural + kinesthetic awareness. Education: avoid repetitive END-range work — check running stride for over-striding into terminal extension, watch pivoting and forceful extension; keep exercises MID-range until asymptomatic with good control. (Rotation strengthening: stool rotations open-chain, closed-chain pivots, then add resistance.)"],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(bullet("**Injections** (still 'conservative'): image-guided (fluoroscopy or ultrasound) intra-articular corticosteroid ± local anesthetic — therapeutic AND diagnostic. The lidocaine logic: pain gone getting off the table → the pain generator is intra-articular → arthroscopy is likely to help; pain unchanged → hunt extra-articular or lumbar sources before anyone operates. (The fluoro procedure confirms placement with a puff of dye first — video linked in the deck.)"));

/* ─────────────── TOPIC 2: ARTHROSCOPY ─────────────── */
k.push(banner("TOPIC 2","Hip Arthroscopy — the Surgery, then the Rehab"));
k.push(spacer());
k.push(h1("1. What Happened in the Operating Room (Why You Care)"));
k.push(bullet("Arthroscopy has largely replaced open dislocation (higher patient-reported outcomes, lower revision rate; open approach risks trochanteric osteotomy nonunion, osteonecrosis, heterotopic ossification, lasting abductor weakness). Sequence: traction on a special table → portals under fluoro → **capsulotomy** (interportal; **T-capsulotomy** for big/distal cam lesions; periportal to spare the iliofemoral ligament) → central compartment first: loose bodies, **acetabular rim resection** for pincer (**>4-6 mm over-resection → iatrogenic dysplasia**, raised contact pressures, early OA), **labral repair** — consensus now prefers repair/fixation over debridement alone (better outcomes at ~3.5 years) — or **reconstruction** with graft (gracilis, semitendinosus, quad tendon, ITB, allograft) when tissue is deficient; in patients **≥40, reconstruction beat repair** (lower failure rate). Then off traction, flex the hip, peripheral compartment: **cam osteoplasty** in the safe zone marked by the lateral synovial fold — protecting the **medial femoral circumflex artery (82% of femoral head supply)**; over-resection risks losing the labral suction seal or fracturing the neck. Capsule closure is surgeon's choice — imperative if hypermobile."));
k.push(bullet("**Restrictions track the procedure**: osteoplasty / labral repair / chondroplasty → weight-bearing + ROM restrictions ≈ **3 weeks**; **microfracture → ~5-6 weeks** of protected WB + longer CPM (protect the clot-turned-fibrocartilage); **iliopsoas Z-lengthening → no straight-leg raises ×4 weeks**. Protocol reporting in the literature is thin and inconsistent — no protocol has won; the standard of care is a **phase-based** program."));
k.push(h1("2. The Philippon Protocol Highlights (full document in the module folder)"));
k.push(bullet("**Circumduction** is the signature move: 5 min clockwise + 5 min counterclockwise in ~70° flexion AND in neutral (20 min total), **2×/day for 2 weeks** (then 1-2×/day to week 10, standing self-circumduction weeks 11-14) — gentle motion without distraction (the leg spent surgery in traction; don't add more). **Isometrics until off crutches**: TA activation, glute squeezes, quad sets, adduction ball squeeze / abduction into a RIGID belt (not a TheraBand — no clamshells yet, no movement, just contraction). **Upright bike, NO resistance, ≤20 min 2×/day** from the start (resistance ~week 7). Quadruped rocking (gentle — respect the 90° flexion zone), **passive IR daily (~20 reps) but NO early ER** until capsular protection lifts. Then: stool/standing rotations → resistance; aqua jogging with buoyancy belt; glute progression (squeezes → standing abduction-with-IR → balance work → single-leg RDL); core ladder (TA → heel march → bent-knee fallout → curl/plank); functional-activity tables for walking, hiking, running, golf — print it for the patient."));
k.push(h1("3. The 2023 Four-Phase Framework ★ (your clinic reference)"));
k.push(detail(["Phase","Contents"],[
 ["**1 — Protect (wk 0 to 4-6)**","Goals: protect the repair, calm pain/inflammation, ~80% ROM. **20% foot-flat WB ×2 wk** (assistive device; microfracture = 6 wk). Avoid: low soft chairs, sitting >30 min, pivoting on the leg, crossing legs, walking-for-exercise, **active SLR**. ROM caps: 120° flexion, 45° abduction, extension to 0°, **NO ER**. Circumduction 2×/day, PROM, STM; glute med/deep rotator activation; **prone lying 1-2 h/day** (keeps the iliopsoas long and off the anterior capsule); upright bike 20 min; pool. CPM/brace per surgeon. Progress when: normalized gait, minimal pain, full WB — and ≥4 weeks respected"],
 ["**2 — Restore (≈ wk 4-8 to 6-12)**","Kill compensations, regain ADL independence, build endurance. Restrictions withdrawn — but **don't rush** (hip flexor + adductor irritation are the classic flare-ups); **no treadmill**. Circumduction to week 10; graded **posterior + inferior** glides (NOT anterior — that capsule was repaired); closed-chain bilateral → unilateral, single-leg balance, core, bike + resistance → elliptical/pool. Pitfall: the patient feels great and goes for a run. Progress when: normal gait, quiet joint, full ROM, good control"],
 ["**3 — Build (≈ wk 8-12 to 12-20)**","Individualized return toward pre-injury life: strength, endurance, neuromuscular + cardiovascular capacity. Avoid excessive volume/force, skimpy rest, ballistic stretching, contact, high velocity. Treadmill WALKING from week 12 (anti-gravity treadmill earlier if available). Progress/discharge when: pain-free full ROM, phase-3 exercises clean, **no Trendelenburg**"],
 ["**4 — Return to sport (≥ wk 12-20)**","Individualized sport program; physician clearance (mandatory for adolescents); criteria ladders for running → agility → sprint/cut → sport. **Vail Sport Test**: 4 cord-resisted tasks — single-leg squat 3 min, lateral bounding 3×30 s, forward jog 2 min continuous, backward jog — scored per minute; **pass = 46/54**; good reliability, partial validity support"]],[2600,6760]));
k.push(tnote("The universal recipe across protocols: patient education + hip muscle exercise + manual therapy + functional exercise + trunk work + cardiovascular training. No running or sport before 12 weeks. Full recovery lives anywhere from 6 to 12 months — say that out loud at evaluation, before the week-8 'I feel awesome' relapse."));

k.push(pageBreak());
/* ─────────────── TOPIC 3: EXTRA-ARTICULAR ─────────────── */
k.push(banner("TOPIC 3","Extra-Articular Conditions of the Hip"));
k.push(spacer());
k.push(bullet("Shared logic: symptoms localize to the involved structure, **provocation tests confirm**, and treatment follows one arc — calm irritability (activity modification + education) → mobilize what's tight (soft tissue/joint, if irritability allows) → **strengthen** (isometric → concentric → eccentric → functional) → retrain movement. Differentials always include the intra-articular list (FAI, microinstability, OA) — and these conditions coexist happily."));
k.push(detail(["Condition","Recognition + the treatment twist"],[
 ["**Iliopsoas complex / internal snapping hip** (coxa saltans interna)","Tendon snaps over the femoral head/capsule (iliopectineal bursa underneath). Overuse in repetitive sagittal motion — runners, kickers, dancers, hockey. Anterior hip pain + audible/palpable snap with flexion-extension (snapping WITHOUT pain is common and benign). Palpate deep in the femoral triangle; Thomas test for anterior tightness; strength-test iliopsoas, rectus, TFL. Treat: modify the snapping arc (bike/elliptical/pool instead), iliopsoas stretching + STM/dry needling as irritability allows, then graded hip-flexion strengthening (short-lever supine marching → sitting → standing → speed + eccentrics). Refractory → injection or surgical lengthening"],
 ["**Adductor strain**","Adductor LONGUS first (then magnus, gracilis) — soccer + hockey; kicking's rapid extension→flexion transitions and skating's eccentric loads. Risk factors: **prior groin injury (2× risk)**, <18 off-season skate sessions, **adduction:abduction strength ratio <80%**, weak lower abdominals. Palpate distally where tendons are distinct (linea aspera / adductor tubercle / pes anserine); abduction ROM should exceed 40°; **isometric adductor squeeze** at 45° and 0° — pain in NEUTRAL squeeze contraindicates return to sport. Treat: restore the >80% ratio, graded isometric→concentric→eccentric into full frontal-plane range, then sport-specific trunk-hyperextension + thigh-abduction patterns"],
 ["**Athletic pubalgia** ('sports hernia' — misnamed: no hernia)","Adductor injury + posterior inguinal wall / distal lower-abdominal attachment injury. Cluster: deep exertional groin pain easing with rest, tenderness 2-3 cm lateral to the pubic tubercle, pain with resisted adduction AND resisted crunch. Emphasize LOWER ABDOMINAL strengthening or the plan fails. Differential is long: femoral neck/pubic ramus stress fracture, osteitis pubis, hip-flexor/hamstring tendinopathy, pelvic floor, obturator nerve entrapment, upper-lumbar radiculopathy"],
 ["**Greater trochanteric pain syndrome (GTPS)**","Bursa + proximal ITB + glute med/min tendons under compressive-tensile overload from repeated **adduction + IR in weight-bearing**. Women 40-65 + young athletes with the risky pattern. Can't lie on that side; pain with stairs/standing/walking. Tests (all provocation, high Sn + Sp): **gluteal de-rotation**, **30-s single-leg stance**, FABER; step-down for control. Treatment heresy worth memorizing: **STM and stretching have weak evidence and can WORSEN it** (more compression) — the winner is **progressive abductor strengthening** (isometric → clamshells → weight-bearing → motor control), plus decompression education: pillow between knees, no leg-crossing or hip-hang standing, no cambered-road running, weight loss when relevant"],
 ["**Piriformis syndrome**","Buttock pain worse with sitting ± sciatic radiculopathy (nerve runs beneath — anatomic variants raise risk). Palpate deep to glute max between sacrum and trochanter (fibers perpendicular to max). **Active + seated piriformis tests** together; step-down catches the eccentric-control deficit (piriformis abducts the FLEXED hip). Treat: decompress (no crossed legs, no wallet-sitting, watch adduction+IR), cautious STM (stop if symptoms peripheralize), stretch in deep flexion + ER + adduction, strengthen glutes so the piriformis can stop compensating"],
 ["**Ischiofemoral impingement (IFI)**","Rare; think of it when everything else is ruled out. Ischiofemoral space **<20 mm** → lesser trochanter and ischium pinch the **quadratus femoris** in hip EXTENSION. Deep gluteal pain in terminal stance; associations: coxa valga, dysplasia, degenerative change, post-fracture/THA. Tests: **long-stride walking** (pain at terminal stance), sidelying passive-extension IFI test, seated slump for sciatic irritability, gait video. Treat: preserve the space — activity modification (sometimes permanent if bony), abduction mobilizations, adductor stretching IN EXTENSION, frontal-plane strengthening (abductors, deep ERs, lumbopelvic) into dynamic control"]],[2500,6860]));

k.push(pageBreak());
/* ─────────────── TOPIC 4: PEDIATRIC ─────────────── */
k.push(banner("TOPIC 4","Pediatric Hip Disorders — a Chronological Tour (Dr. Boucher)"));
k.push(spacer());
k.push(bullet("Two framing rules: hip disease **refers to the knee** — a child with knee pain gets a full hip exam, every time; and **age is your best diagnostic filter** (tag the age chart in the deck): DDH at birth-infancy → septic arthritis <2 → transient synovitis 2-10 → Legg-Calvé-Perthes 3-12 → SCFE 10-16."));
k.push(detail(["Condition","Essentials"],[
 ["**Developmental dysplasia of the hip (DDH)**","Shallow, laterally-oriented acetabulum → subluxable/dislocatable head. Screened at birth; mechanical/physiologic/environmental causes (tight swaddling!). After 1 month the only sign may be **limited/asymmetric abduction**. Tests: **Galeazzi** (hook-lying knee heights unequal), **Ortolani** (palpable clunk of relocation with lateral-to-medial glide), **telescoping** (AP shunting of the femur). Treatment = position and wait: **Pavlik harness** (or double-diapering) holds flexion-abduction 'frog-leg' up to ~9 months while the socket models and capsule tightens"],
 ["**Septic arthritis** (<2 yr)","Acute, rapidly progressive pyogenic joint infection: unreasonably irritable infant + infection signs; leg held in **open-pack** (comfort) position. Medical emergency: antibiotics, relative rest, aspiration for pressure, surgical drainage when severe. PT's job is recognition + referral speed"],
 ["**Acute transient synovitis** (2-10 yr)","Non-septic synovitis, often idiopathic, **self-limiting** — but radiographs + follow-up matter because it can precede LCP. Hip pain worse with weight-bearing, ROM loss toward closed-pack, fever possible but not reliable. Manage: relative rest, partial WB, watchful follow-up"],
 ["**Legg-Calvé-Perthes (LCP)** (3-12 yr)","Idiopathic **avascular necrosis of the femoral head**; boys > girls; usually unilateral. Four stages: necrosis/densification (6-12 mo) → fragmentation + resorption (1 yr+) → re-ossification → remodeling (years). Hip/groin pain + **referred pain above the knee**, ROM loss, evolving flexion-rotation contracture. Imaging is gold standard. Goals: reduce irritability, keep the head CONTAINED (prevent extrusion/collapse), regain sphericity → prolonged **abduction + slight IR bracing** (± early casting), plus ROM + strengthening out of the brace"],
 ["**Slipped capital femoral epiphysis (SCFE)** (10-16 yr)","The head slips **posterior-inferior** off the neck through the physis; boys > girls, ~50% bilateral, obesity association, occasional endocrine link. Weight-bearing pain → limp/antalgic gait; ROM limited toward closed-pack; the classic sign: passive flexion **deviates into abduction + ER**. Frog-leg radiographs diagnose; grades by slip: 1 <33%, 2 = 33-50%, 3 >50%. Management scales with grade: traction/gentle reduction → cast → **ORIF with a single central screw**; severe → proximal osteotomy"]],[2700,6660]));
k.push(h1("Sync 6 — Cases to Rehearse"));
k.push(compare("LUCY — 35F soccer coach","SARAH — 29F PT, 1 month post-arthroscopy",
 ["Three months of L LATERAL hip pain after a weekend tournament ('out of shape, overdid it'), worse with coaching drills, stairs, walking — and she **can't sleep on that side** (3-4 h/night). Exam: exquisite greater-trochanter tenderness, 'ropy' warm gluteal tendons, glute med 3+/5 with pain, **+ gluteal de-rotation, + 30-s single-leg stance**, bilateral step-down valgus collapse (painful L). Pattern = **GTPS**: decompress (pillow between knees, sleep position, stance habits), progressive abductor strengthening, fix the step-down — and skip the ITB stretching."],
 ["Two years of R hip/groin pain → scope for **labral tear + FAI** one month ago; motivated, informed, wants hiking/swimming/work back. She's in **phase 1-2 territory**: respect tissue timelines her enthusiasm will want to skip — circumduction, isometrics, no early ER, posterior/inferior glides only, bike before treadmill, 12-week floor on running. Rehearse explaining WHY (three-minute-drill practice: the repair, the capsule, the flexor-irritation trap). Dr. Barrett's runner (26F, 50 mi/wk, anteversion + IR running form, +labral tests, -impingement tests) showed conservative care can win with instability-driven tears; Dr. Bartley's 40-something sports PT (cam FAI + tear → femoroplasty + repair + microfracture) shows PT may not be the whole answer — but it's always part of it."],
 C.blue,C.teal,C.lightBlue,C.lightTeal));
k.push(spacer());
k.push(...glossary("Module 6 Quick-Reference Glossary",[
 ["Cam / pincer / mixed","Head-neck overgrowth (young males) / rim overcoverage (middle-aged females) / both — most symptomatic"],
 ["FAI syndrome","Morphology + symptoms + signs — cam shape alone is common in pain-free athletes (63%)"],
 ["C-sign","Hand cupped above the trochanter — intra-articular pain pattern"],
 ["Labral facts","96% of older adults have tears; 47% no inciting event; anterosuperior most common"],
 ["Microinstability","Capsuloligamentous laxity + symptoms; anterior capsule/iliofemoral insufficiency; ER >60° = laxity clue"],
 ["FADIR / FABER","Flexion-adduction-IR impingement test / flexion-abduction-ER (normal ≈20 cm knee-to-table)"],
 ["Assisted FABER","Active pull toward table; <4 cm gain = bony block (core-assisted norm ≈16 cm)"],
 ["AB-HEER / HEER / prone instability","Instability trio: Sn 80.6/71/33.9, Sp 89.4/85.1/97.9 — cluster them"],
 ["iHOT-33","Young-active hip outcome tool; MIC ≈ 10"],
 ["Capsulotomy types","Interportal · T (big distal cam) · periportal (spares iliofemoral ligament)"],
 ["Rim resection limit","> 4-6 mm risks iatrogenic dysplasia"],
 ["MFCA","Medial femoral circumflex artery — 82% of head blood supply; the cam-resection landmark to protect"],
 ["Microfracture caveat","Longest protection: ~6 wk assistive device, extended CPM"],
 ["Circumduction","Philippon signature: 5 min CW + CCW in flexion and neutral, 2×/day ×2 wk"],
 ["Phase-1 caps","20% FFWB ×2 wk; 120° flexion, 45° abduction, ext to 0°, NO ER; prone lying 1-2 h/day"],
 ["Vail Sport Test","4 cord-resisted tasks; pass = 46/54; ≥12 weeks before running/sport"],
 ["Adductor squeeze","Isometric at 45° and 0°; pain in neutral = no return to sport; target add:abd ratio >80%"],
 ["Athletic pubalgia","Adductor + lower-abdominal/inguinal-wall injury; no actual hernia; train the lower abs"],
 ["GTPS rule","Strengthen abductors, DECOMPRESS; stretching/STM can worsen it"],
 ["Piriformis stretch position","Deep hip flexion + 40-50° ER + 25-30° adduction"],
 ["IFI","Ischiofemoral space <20 mm; quadratus femoris pinched in extension; long-stride test"],
 ["Pediatric age filter","DDH (birth) → septic arthritis (<2) → transient synovitis (2-10) → LCP (3-12) → SCFE (10-16)"],
 ["Galeazzi / Ortolani / telescoping","DDH tests: knee-height inequality / relocation clunk / AP shunting"],
 ["LCP","Idiopathic femoral-head AVN; 4 stages; contain with abduction + slight IR bracing; knee-referred pain"],
 ["SCFE","Posterior-inferior physeal slip; flexion deviates into abduction-ER; grades by % slip; single-screw ORIF"]]));

build(k,"/home/claude/out/Module6_FAIArthroscopyLifespanHip_StudyNotes.docx");
