const L = require('/home/claude/notes_lib.js');
const {C,h1,h2,body,bullet,tnote,tip,compare,detail,infoBox,banner,glossary,fig,pageBreak,spacer,cover,build,linkBox} = L;
const E="/home/claude/emb27/";
const k=[];

k.push(...cover("Therapeutic Interventions I (DPTH 6231)","Module 3: Tissue Mechanics & Needs Analysis",
 "Topics 3.1–3.4 + Sync Session 3 — what tissue does under load, how it heals, and how you choose the intervention",
 ["Dr. Jake Awruch — all four topics, including the three-part Clinical Reasoning series",
  "This is the module where the course stops describing and starts **deciding**. Topics 3.3 and 3.4 give you the framework you will use on every patient for the rest of the programme",
  "The one rule everything reduces to: **treat what you see**"]));

/* ─────────────────────────── TOPIC 3.1 ─────────────────────────── */
k.push(banner("TOPIC 3.1","Tissue Mechanics: Concepts, Bone, Articular Cartilage, Aging"));
k.push(spacer());
k.push(body("Objectives: understand stress-strain curves, viscoelastic properties, stress relaxation, and creep."));

k.push(h1("1. Types of Loading"));
k.push(detail(["Load","What it does","Example"],[
 ["**Compression**","Pushes together","Joint compression — the femur sitting on the tibia"],
 ["**Tension**","Pulls apart","Tendons and ligaments — a high tensile load is the ACL tear mechanism"],
 ["**Shear**","Items slide across each other","The patellofemoral joint — patella sliding across the femur"],
 ["**Torsion**","Twisting along an axis",""],
 ["**Bending**","Tension on one side, compression on the other",""]],[1700,3300,4360]));

k.push(h1("2. Mechanical Property Definitions"));
k.push(detail(["Term","Definition"],[
 ["**Stress**","Force generated by resisting deformation — force ÷ area"],
 ["**Strain**","Ratio of deformed length to original length"],
 ["**Stiffness (Young's modulus)**","Ratio of stress to strain — the slope in the elastic region"],
 ["**Elastic region**","Material returns to its original shape after the load is removed"],
 ["**Plastic region**","Material stays deformed after the load is removed"],
 ["**Yield point**","Where behaviour transitions from elastic to plastic"],
 ["**Ultimate failure point**","Where the material breaks"],
 ["**Energy**","Area under the stress-strain curve — can be stored or dissipated"]],[2700,6660]));
k.push(tnote("Think of the yield point as the point of no return — it's the inflection point. And the ultimate failure point is the other one."));
k.push(...fig(E+"ldc.png",1650,900,"Load-deformation curve: A–B elastic, B–C plastic, B the yield point, C ultimate failure (Topic 3.1 handout)"));
k.push(...fig(E+"ssc.png",1650,900,"The same curve in tissue terms — slack, elastic, plastic, failure (Topic 3.1 handout)"));
k.push(bullet("Reading the curve in tissue terms: first **slack is taken up** and the fibres straighten. Then the **elastic region** — safe, reversible stretch, like an elastic band. Then the **plastic region** — permanent change. Then **failure** — the tissue breaks."));
k.push(tip("The reason any of this matters: this is exactly what happens when an athlete tears something. The deck uses Kevin Durant rupturing his Achilles in the NBA Finals as the picture of ultimate failure."));

k.push(h1("3. Viscoelasticity, Creep and Stress Relaxation"));
k.push(detail(["Term","Definition"],[
 ["**Viscoelastic**","Behaviour changes with the **rate of loading** — it is velocity dependent. Load it faster and it behaves differently"],
 ["**Creep**","Under a **constant load**, the material deforms and reaches an equilibrium state. Rapid initial deformation, then slow deformation until equilibrium"],
 ["**Stress relaxation**","Under a **constant deformation**, stress builds initially then slowly decreases to equilibrium. It distributes the stress across the tissue — protective"],
 ["**Biphasic**","Contains components with different properties (fluid + solid, organic + inorganic)"],
 ["**Anisotropic**","Mechanical properties differ between loading modes — behaves differently in tension than in compression"]],[2400,6960]));
k.push(tnote("Creep over a lifetime: as someone ages, the vertebrae eventually shrink in height. That's a form of creep — which is why older people are shorter than they were when they were younger."));
k.push(tnote("Stress relaxation, made physical: stand on a bed. Your foot sinks in until it stops sinking in, and you're not breaking the bed either — it's just supporting you. That's stress relaxation."));
k.push(tip("Dr. Awruch flags biphasic and anisotropic as nice-to-know rather than need-to-know. Creep, stress relaxation and rate-dependence are the three the handout lists as take-home."));
k.push(tnote("One forward-looking point he makes: just because something hurts, it doesn't mean there is something structurally wrong. Not very relevant for this class — very relevant later."));

k.push(...glossary("Quick-Reference Glossary — Topic 3.1",[
 ["Compression / tension / shear / torsion / bending","The five loading modes"],
 ["Stress","Force per unit area generated resisting deformation"],
 ["Strain","Deformed length ÷ original length"],
 ["Stiffness","Stress ÷ strain; the slope of the elastic region"],
 ["Elastic region","Reversible deformation — returns to original shape"],
 ["Plastic region","Permanent deformation"],
 ["Yield point","Transition from elastic to plastic behaviour"],
 ["Ultimate failure point","Where the material breaks"],
 ["Viscoelastic","Rate-of-loading dependent behaviour"],
 ["Creep","Progressive deformation under a constant load"],
 ["Stress relaxation","Decreasing stress under a constant deformation"],
 ["Biphasic","Containing components of differing properties"],
 ["Anisotropic","Properties differ depending on the direction of loading"]]));
k.push(pageBreak());

/* ─────────────────────────── TOPIC 3.2 ─────────────────────────── */
k.push(banner("TOPIC 3.2","Stages of Healing"));
k.push(spacer());
k.push(body("Objectives: discuss the phases of tissue healing, and apply the phases to cases across different tissues."));

k.push(h1("1. Types of Injury"));
k.push(detail(["Injury","What it is"],[
 ["**Strain**","Musculotendinous unit — a pulled muscle. The classic one"],
 ["**Sprain**","Ligamentous injury, **grades I–III** — the grade goes up as more of the ligament is damaged"],
 ["**Dislocation**","Loss of anatomical relationship of the joint"],
 ["**Subluxation**","Partial dislocation — think of it as a short-term dislocation"],
 ["**Muscle/tendon rupture or tear**","Partial or complete"],
 ["**Tendinopathy**","Tendon injury affected by mechanical loading — **tendinitis** acutely, **tendinosis** when it has been going on longer (inflammation, or inflammation with scar tissue)"]],[2400,6960]));
k.push(tnote("On complete tears: it's not actually what you think. Sometimes a full tear just means it went completely through — it doesn't mean it's completely torn off."));
k.push(detail(["Condition","What it is"],[
 ["**Synovitis**","Inflammation of a synovial membrane — e.g. a tendon sheath that exists to reduce friction, which sometimes gets inflamed itself"],
 ["**Hemarthrosis**","Bleeding into the joint (*heme* = blood, *arthrosis* = of the joint)"],
 ["**Ganglion**","Tendon or joint capsule wall ballooning — the classic ganglion cyst on the back of the hand"],
 ["**Bursitis**","Inflammation of a bursa. Harder to see; often a diagnosis of exclusion on orthopaedic exam"],
 ["**Contusion**","Bruising from trauma"],
 ["**Overuse / cumulative trauma**","Repetitive low loads resulting in inflammation and pain"]],[2400,6960]));
k.push(tnote("Two places Dr. Awruch corrects his own slide. First, he'd retitle this from 'types of injuries' to just 'conditions' — not all of these happen via an injury. Second, on overuse he'd drop the word 'low': common sense says repetitive HIGH loads cause overuse too."));

k.push(h1("2. SINSS"));
k.push(...fig(E+"sinss.png",1650,900,"SINSS — the clinical decision-making frame (Topic 3.2 handout)"));
k.push(detail(["Letter","Meaning","What it buys you"],[
 ["**S** — Severity","How intense and impactful is this in the person's life","Determines the appropriate vigour and extent of the examination and the interventions"],
 ["**I** — Irritability","What aggravates it, what eases it","Same — sets how much you can do"],
 ["**N** — Nature","The body system in question","Directs the focus of the exam, the intervention, and whether referral is needed"],
 ["**S** — Stage","**Acute** (<6 weeks) · **subacute** (6–12 weeks) · **chronic** (>12 weeks)","Identifies the stage of healing, which guides the corresponding intervention"],
 ["**S** — Stability","Improving, worsening, or not changing","Identification of influencing factors"]],[1900,3200,4260]));
k.push(tnote("On the timeframes: there are different definitions, but what he's seen most is under 6 weeks acute, 6–12 weeks subacute, over 12 weeks chronic — with some discrepancy in the literature."));
k.push(tip("The stability point is the one with real clinical teeth. If a patient improves from visit 2 to 3 and again from 3 to 4, they will likely keep improving. If they keep getting worse over a long course of care, that's your cue to ask why, and to consider referral."));
k.push(tnote("Why stage matters so much: if you know there's a soft-tissue injury to a muscle, and you know the tissue healing timeline for muscle, you can accurately predict when it's safe to start isometric strengthening and then isotonic strengthening."));

k.push(h1("3. The Four Phases"));
k.push(...fig(E+"phases.png",1650,700,"Hemostasis → inflammation → proliferation → remodeling (Topic 3.2 handout)"));
k.push(detail(["Phase","What is happening","What you see on exam","Duration"],[
 ["**Inflammation**","Vascular, cellular, chemical and immune processes; cells, chemical changes, immune cells and fibroblasts rush to the area","**Swelling, redness, warmth** (signs) and **pain** (symptom). Movement is painful; PROM may produce muscle guarding before end range","**4–6 days**"],
 ["**Proliferation & repair**","Noxious and inflammatory chemicals removed; capillary growth; collagen and granulation tissue form","Decreased swelling, inflammation resolving. **Pain at end-range resistance** with ROM, and weakness","**10 days – 6 weeks**, longer in tissues with poor vascularity"],
 ["**Maturation / remodeling**","Connective tissue maturation, scar tissue contracture, **conversion of Type III collagen**, reorganisation with stress","Inflammation completely resolved. Pain only at end range of available motion, past resistance. Weakness can persist","**6–12 months**, variable with severity and tissue"]],[1800,2900,2700,1960]));
k.push(tnote("The postoperative version of the inflammatory phase: you get a patient after a rotator cuff repair, you go to do passive range of motion, and they say stop pulling, it's really painful. You might even feel some spasm — they're just uncomfortable moving into that new range."));
k.push(tip("Why the 6-week mark keeps appearing in protocols: in a lot of postoperative protocols strengthening doesn't start until six weeks, which is the end of the proliferation window. Some physicians add an extra week on top."));
k.push(tnote("On the 6–12 month maturation window: on paper it might last 12 months, but watching a patient perform, they're likely significantly stronger by month six or eight. You might need until the end of the year for full gains."));

k.push(h1("4. PT Goals by Phase"));
k.push(detail(["Phase","Goal","Do","Precautions / contraindications"],[
 ["**Inflammation**","**Maximum protection**","Control the effects of inflammation (pain) · prevent the adverse effects of rest · cautious progression of movement · protective and assistive devices as indicated","**Contraindicated: stretching and resistance exercise to inflamed tissue**"],
 ["**Proliferation**","**Moderate protection / controlled motion**","Scar mobilisation · promote healing · progress ROM with caution · progress exercise intensity","Increased inflammation, or **pain lasting > 24 hours**"],
 ["**Maturation**","**Minimal protection / return to function**","Improve scar quality · increase strength and endurance · function-specific exercise · progress to return to work or play for high demand","**No inflammation, or pain > 4 hours, or pain requiring medication**"]],[1700,2200,3200,2260]));
k.push(tnote("A distinction worth writing down: in the inflammatory phase he would replace 'stretching' with 'range of motion'. Range of motion is typically fine — stretching, meaning actively trying to gain range, is not. And the great thing about the resistance-exercise contraindication is that if you tried, the patient would tell you it hurts anyway."));
k.push(tnote("On working inside a protocol, in the proliferation phase: if the protocol says you may move the shoulder to 110°, those are your parameters — but that doesn't mean you have to go to it. Tell the patient we're allowed to take you to 100°, let me know if it hurts before we get there, and let me know if you want me to stop."));
k.push(infoBox("Individualise to the patient",[
 "These are **general timeframes** — health and lifestyle will change them",
 "Setbacks happen. Communicate and go back to the drawing board",
 "Understand your patient's factors; **education is key**",
 "Not every patient comes from a physician — with direct access you are the first one, so know the timelines and communicate",
 "Usually the patient will tell you when they feel ready for the next stage"],C.teal,C.lightTeal));
k.push(tnote("The photo of the forest is there on purpose: in PT school information comes in pieces, and when you see a case it's easy to clutch onto one item or one test instead of stepping back. As you learn more you may find you're sure of less — and that's okay. See the forest through the trees."));

k.push(...glossary("Quick-Reference Glossary — Topic 3.2",[
 ["Strain vs sprain","Musculotendinous injury vs ligamentous injury"],
 ["Subluxation","Partial dislocation"],
 ["Tendinitis vs tendinosis","Acute tendon inflammation vs longer-standing tendon change with scar tissue"],
 ["Synovitis","Inflammation of a synovial membrane or sheath"],
 ["Hemarthrosis","Bleeding into a joint"],
 ["Ganglion","Ballooning of a tendon sheath or joint capsule wall"],
 ["SINSS","Severity, Irritability, Nature, Stage, Stability"],
 ["Acute / subacute / chronic","<6 weeks / 6–12 weeks / >12 weeks"],
 ["Hemostasis","The first phase of healing — bleeding is stopped"],
 ["Granulation tissue","New connective tissue and capillaries forming during proliferation"],
 ["Type III collagen conversion","Remodeling of immature collagen into mature, organised tissue under stress"],
 ["Contracture","A muscle or joint becoming fixed in a shortened position"]]));
k.push(pageBreak());

/* ─────────────────────────── TOPIC 3.3 ─────────────────────────── */
k.push(banner("TOPIC 3.3","Needs Analysis"));
k.push(spacer());
k.push(body("Objectives: identify the impairment bucket, identify the necessary task demands, identify the treatment bucket, and apply to cases."));
k.push(...fig(E+"buckets.png",1650,900,"The three impairment buckets and what each one needs (Topic 3.3 handout)"));

k.push(h1("1. The Impairment Bucket"));
k.push(detail(["Bucket","Treatment"],[
 ["**1. Weakness**","**Strengthening**"],
 ["**2. Mobility**","**Mobilization**"],
 ["**3. Pain**","**Treat the pain**"]],[4200,5160]));

k.push(h2("Bucket 1 — Weakness"));
k.push(bullet("Two different presentations both land here: **decreased strength** and **hypermobility**. Both are treated with strengthening."));
k.push(compare("HISTORY — DECREASED STRENGTH","HISTORY — HYPERMOBILITY",
 ["“I get really fatigued and tired”","“It's hard to do” · “difficulty”","**Time of day is NOT consistent** — worse at the end of the day, or pain only at certain times"],
 ["“I've been double jointed since I was a kid”","“Clicking and popping” — e.g. a swimmer with shoulder symptoms","“I've had dislocations in the past”"],
 C.blue,C.purple,C.lightBlue,C.lightPurple));
k.push(detail(["Exam finding","What you may see"],[
 ["**AROM**","Maybe decreased — they can't lift the joint because they're too weak"],
 ["**PROM**","Could be **increased** — they're hypermobile"],
 ["**MMT / myotome**","Decreased strength"],
 ["**Functional movements**","Decreased quality — squat, lunge, single-leg squat. Watch a single-leg squat and see the knee wobbling"],
 ["**Joint mobs**","Normal or hypermobile"]],[2200,7160]));
k.push(bullet("**Findings, either/or:** decreased strength, **OR** increased ROM = hypermobile."));

k.push(h2("Bucket 2 — Mobility"));
k.push(bullet("**History:** “hard to move it” · “feels tight” · “feels stuck” · “I can't” — and crucially, **the same story any time of day**."));
k.push(tnote("Why the time-of-day question separates the first two buckets: if something is tight, it's going to be tight consistently. Someone getting tired after being at work all day is a very different story, and that points toward decreased strength."));
k.push(bullet("**Exam:** PROM decreased · joint mobilization **hypomobile**. **Findings:** hypomobility on joint mobs, decreased ROM, and sometimes a **firm end feel**."));
k.push(bullet("The cause is either the joint being tight or soft tissue restriction — so the treatment is stretching or mobilization."));

k.push(h2("Bucket 3 — Pain"));
k.push(bullet("**History:** pain and/or fear — “it hurts when…” · “I worry that…” · “I don't want to make it worse, so I don't move.”"));
k.push(bullet("**Exam:** **empty end feel** on ROM — pain well before end range. On MMT, pain or fear limits effort. **Finding:** painful, and possibly afraid of the pain."));

k.push(h1("2. Necessary Task Demands"));
k.push(compare("STRENGTH → STRENGTHEN","MOBILITY → MOBILIZE",
 ["**Clinical principle: if it is NOT a mobility requirement, then by default it is a strength requirement.** Strength is the default bucket","Everything here requires **active muscle contraction**: power · agility · motor control · endurance · coordination · balance","Sprinter → power and endurance. Soccer player → agility. Powerlifter → power. Century-ride cyclist → endurance"],
 ["**Simple as this: how much ROM does the task require?**","**You only need enough ROM to do the task.** A sprinter needs no more range than sprinting requires; a marathoner needs enough for the gait they run with. That's it","If a patient already has enough range for their task, they **default into the strength bucket** and come out of the mobility bucket — range is checked off, so the remaining limitation must be strength"],
 C.green,C.teal,C.lightGreen,C.lightTeal));

k.push(h1("3. Putting It Together"));
k.push(infoBox("Impairment bucket + task demands = treatment bucket",[
 "**Is ROM sufficient?** Compared to normal, AND for the task needed",
 "**Is strength sufficient?** Compared to normal, AND for the task needed",
 "**The task demands can outweigh the impairment bucket**"],C.gold,C.lightGold));
k.push(tnote("Two examples of task demand outweighing the impairment: someone with 5/5 MMT does not necessarily have enough strength to be an Olympic weightlifter. And a competitive cyclist with 5/5 strength on testing still may not be able to ride a hundred miles — that task demands endurance, not just strength."));

k.push(h1("4. The Two Cases"));
k.push(detail(["Case","Findings","Reasoning"],[
 ["**Judi**, 16, high school swimmer. Bilateral shoulder pain, worse during swim season. Clicking and popping. Dislocated both shoulders years ago doing different sports","Joint mobility hypermobile in **all shoulder planes** · ROM hypermobile (she doesn't stop at 180° of flexion, she keeps going; external rotation the same) · **positive Beighton score**","She already has **more** mobility than she needs. Stretching would only make it worse. She needs **strengthening**"],
 ["**Christina**, 26, runner, PT student. No pain at rest or during her day, but knee pain from about **mile 8** while training for the Boston marathon, resolving after the run","ROM normal · joint mobility normal · MMT deficits in quadriceps, hamstrings and hips (4+/5)","Pain arrives **with fatigue**, not consistently — that's the weakness pattern. **Strengthening bucket**, not stretching and not pain-based treatment"]],[2800,3400,3160]));

k.push(...glossary("Quick-Reference Glossary — Topic 3.3",[
 ["Impairment bucket","Weakness, mobility, or pain — what the exam actually found"],
 ["Necessary task demands","What the person needs to be able to do; strength or mobility"],
 ["Treatment bucket","Impairment bucket + task demands"],
 ["Hypermobility","Range of motion beyond normal limits"],
 ["Beighton score","A nine-point screen for generalised joint hypermobility"],
 ["Hypomobility","Less accessory or physiological motion than normal"],
 ["Firm end feel","The end-range sensation of tissue tension — typical of a mobility deficit"],
 ["Empty end feel","The patient stops the movement because of pain before any tissue resistance is felt"]]));
k.push(pageBreak());

/* ─────────────────────────── TOPIC 3.4 ─────────────────────────── */
k.push(banner("TOPIC 3.4","Intervention Decision Making — Clinical Reasoning 1–3"));
k.push(spacer());
k.push(body("A three-part series. The stated starting point is “**it depends**” — and the point of the series is to turn that into a repeatable decision."));

k.push(h1("1. What Range of Motion Tells You (Part 1)"));
k.push(detail(["Finding","What it means","So…"],[
 ["**AROM normal and pain-free**","You can **rule that joint out** as the pain generator — full range, normal end feel, no pain","Add overpressure (effectively PROM) to confirm. Surrounding musculature can still be involved"],
 ["**AROM < PROM**","A **muscle power impairment** — power is impaired, which means weakness","**Strengthening** may be a great antidote"],
 ["**AROM limited, and PROM can't make up the difference**","Some form of **tightness** — a mobility impairment","**Stretching or mobilization**"]],[2400,3400,3560]));
k.push(bullet("If **AROM is limited**, there are three possibilities: **weakness, tightness, or pain** — plus a fourth factor, **fear**."));
k.push(bullet("If **PROM is limited or painful**, it is one of three things: a **joint mobility deficit**, a **tissue extensibility deficit**, or **pain**. It is **not weakness** — passive motion doesn't involve muscle activation, because you are producing the movement."));
k.push(tnote("On fear: if someone was hurt previously, the brain remembers that experience, similar to other forms of trauma. After a car accident a person may be fearful the next time they drive on the highway. That fear alone can limit movement."));
k.push(tip("The telehealth argument for why ROM is so valuable: you can't put hands on the patient or perform orthopaedic tests, so you're doing a detailed subjective history and observing range of motion — and you're still getting about 95% of the information you'd normally get in clinic."));
k.push(tnote("The musculoskeletal screen and the neuro screen are performed together. They're taught in isolation in a neuro class and a musculoskeletal class, but they are not performed in isolation — nerves activate and control muscles, and any pain felt is regulated by the nervous system."));

k.push(h1("2. Matching Finding to Intervention (Part 2)"));
k.push(detail(["Finding","Pairs with"],[
 ["**Weakness**","Strengthening"],
 ["**Pain**","Pain-focused treatment"],
 ["**Fear**","Psychologically informed physical therapy"],
 ["**Joint mobility deficit**","Joint mobilization or manipulation"],
 ["**Tissue extensibility deficit**","Stretching"]],[3400,5960]));
k.push(tnote("Tightness has exactly two sources. Tissue extensibility deficits is a bucket term for anything soft-tissue — muscle, ligament, nerve, scar tissue. Joint mobility deficits mean the joint itself lacks mobility."));
k.push(infoBox("The ankle worked example — why precision matters",[
 "Limited dorsiflexion could be **tissue extensibility** (soleus, posterior tibialis, anything behind the ankle) or a **joint mobility deficit** (talocrural joint)",
 "If the **soleus** is what's limiting it, mobilising the talocrural joint doesn't address the problem",
 "If the **talocrural joint** is tight and the soleus and gastroc aren't, mobilising the joint is exactly right",
 "It isn't dangerous to mobilise something that isn't tight — it's just unnecessary. **You're using the wrong tool**"],C.blue,C.lightBlue));
k.push(tnote("The screwdriver analogy he keeps coming back to: if you needed a Phillips head but were given a flat head, you simply would not be able to target what you needed to target."));
k.push(bullet("**Weakness has two flavours too.** Muscle-related — quadriceps testing 3+/5, so a long arc quad targets the quadriceps in that same position. Or **motor control** — a single-leg squat showing knee and hip adduction, **valgus collapse**, which is a combination of strength deficits, motor control deficits and likely hip abduction weakness. You strengthen those areas AND retrain the movement."));
k.push(tnote("On pain being inhibitory: if you've ever stepped on a pebble barefoot, you probably noticed your knee buckle immediately. Pain causes rapid inhibition — it essentially short-circuits the quadriceps and the muscles needed to load the limb. That's why your leg may feel weaker the day after a knee injury even though nothing is torn."));
k.push(tip("Do not treat what you do not see. A hypermobile gymnast with low back pain does not need a flexibility exercise — if nothing is tight, what exactly are you stretching? Stretching cannot fix tightness that is not present."));

k.push(h1("3. The Interventions Themselves (Part 3)"));
k.push(detail(["Intervention","Forms","When"],[
 ["**Joint mobilization**","Self-mobilization (e.g. foam roller for limited thoracic extension) · manual therapy mobilization · manipulation","Joint mobility deficit"],
 ["**Stretching**","Self-stretch · therapist-performed manual stretching · massage or instrument-assisted soft tissue mobilization (IASTM)","Tissue extensibility deficit"],
 ["**Manual therapy**","**Does two things: increases ROM and reduces pain**","Tight joint, or a painful joint where the patient is having trouble relaxing"],
 ["**Psychologically informed care**","CBT · graded exposure · relaxation therapy · pain neuroscience education · **activity pacing**","High pain, debilitating pain, fear avoidance, chronic pain"],
 ["**Strengthening**","Resistance training → motor control → power → running, cutting and return-to-sport drills","Weakness, and often indirectly as graded exposure"]],[2000,4400,2960]));
k.push(compare("MOBILIZATION","MANIPULATION",
 ["**Low velocity** — slow, controlled force applied over time","Gently applying force to get the segment moving and potentially reduce pain","Larger amplitude is possible because it's slow"],
 ["**High velocity, low amplitude**","Very fast, and the amplitude is quite low — possibly lower than a mobilization","Move something quickly and it must be a very small movement. **Large, fast movements are where things become unsafe**"],
 C.blue,C.red,C.lightBlue,C.lightRed));
k.push(tnote("The CrossFit worked example for stretching: he struggles to keep his arms overhead at the bottom of an overhead squat. At the bottom the latissimus dorsi is wound up on both ends — it attaches to the pelvis and to the shoulder, so it's a bi-articular muscle. Home exercise, soft tissue work, IASTM, or a foam roller."));
k.push(infoBox("Activity pacing — breaking the boom-bust cycle",[
 "The pattern: overactivity → injury and pain → **a lot of rest** → return full steam → overactive again → pain again → rest even longer → **weaker** → repeat",
 "Instead of the full activity that causes pain — running eight miles — you have them run **two**",
 "Rest an appropriate amount, **not long enough to become weaker**, then return to the same activity",
 "Gradually progress. This is how you move patients out of chronic pain"],C.purple,C.lightPurple));
k.push(tnote("On why strengthening works when you might not expect it: knee pain often responds well to hip strengthening as well as hamstring and quadriceps strengthening. But when pain is the primary issue and pain levels are high, strengthening may not be realistic or appropriate initially."));
k.push(bullet("**Why the strengthening order matches protocols:** look up an ACL reconstruction protocol and you'll see restore range of motion → strengthen → motor control → power → running → return to sport, all while respecting tissue healing timelines."));

k.push(h1("4. The Whole Framework, One Picture"));
k.push(...fig(E+"framework.png",1650,1000,"The integrated decision framework from Clinical Reasoning Part 3 — start at the body region in question, work down through AROM and PROM to an intervention"));
k.push(bullet("Start at the **body region in question**. Assess **AROM** — full and pain-free rules the joint out. If limited or painful, gather more: assess **PROM** to separate weakness from tightness from pain or fear. **PROM full and pain-free → strengthen.** PROM limited or painful → address the limitation, or the pain, or the fear."));
k.push(tnote("This can feel overwhelming, but slow down and recognise that you already know this information. All I have done is organise it into a systems-level framework that mirrors how clinicians think."));
k.push(tip("If it ever feels like too much, the whole series collapses to one rule: TREAT WHAT YOU SEE. Weakness → strengthening. Tightness → stretching or joint mobilization. Pain and fear → pain modulation and psychologically informed PT."));

k.push(h1("5. The Four Part-2 Cases"));
k.push(detail(["Patient","Presentation","If you could do only ONE thing"],[
 ["**Lauren**, 36, fell on an outstretched arm skiing. Left shoulder pain","AROM: can't reach overhead fully (beyond ~125°) · **PROM full** · resisted ER weak and mildly painful · flexion 2+/5 · resisted IR normal","**Rotator cuff strengthening.** PROM is full so there's no tightness; her pain is mild and she isn't fearful"],
 ["**Olivia**, 26, ballet dancer, fell on her patella. Severe knee pain","X-rays negative · ROM limited to 95° flexion **due to pain**","**Address the pain.** Strengthening or stretching would likely make things worse at this stage"],
 ["**Sarah**, 23, three weeks post knee arthroscopy. Fearful of bending the knee, worried about 'ruining the surgery' (a teammate needed a second surgery)","ROM −10° extension to 95° flexion · **no end feel**, but she grimaces and asks you to stop · she says **it doesn't hurt at all** — she's afraid it might","**Psychologically informed physical therapy.** The limiter is fear, not tissue"],
 ["**Brian**, 55, knee osteoarthritis with tight hamstrings and quadriceps","ROM limited with a **firm end feel** and minimal pain","**Stretching and joint mobilization**"]],[2300,3600,3460]));

k.push(...glossary("Quick-Reference Glossary — Topic 3.4",[
 ["Muscle power impairment","AROM less than PROM — the difference is weakness"],
 ["Joint mobility deficit","Restriction arising from the joint itself"],
 ["Tissue extensibility deficit","Restriction arising from soft tissue — muscle, ligament, nerve, scar"],
 ["Overpressure","Passive force added at the end of active range to confirm a normal end feel"],
 ["Valgus collapse","Knee and hip adduction under load, seen on single-leg squat"],
 ["Mobilization","Low-velocity passive joint technique"],
 ["Manipulation","High-velocity, low-amplitude passive joint technique"],
 ["IASTM","Instrument-assisted soft tissue mobilization"],
 ["Psychologically informed PT","Care addressing fear, avoidance and pain beliefs — CBT, graded exposure, pain neuroscience education, activity pacing"],
 ["Activity pacing","Sub-threshold activity with controlled rest, progressed over time, to break the boom-bust cycle"]]));
k.push(pageBreak());

/* ─────────────────────────── SYNC ─────────────────────────── */
k.push(banner("SYNC SESSION 3","Needs Analysis & Clinical Reasoning",C.teal));
k.push(spacer());
k.push(body("The session opens with three questions to argue about: **when would a patient benefit from joint mobilization vs stretching? How about strengthening? Manual therapy?**"));

k.push(h1("1. The Five-Step Method"));
k.push(infoBox("The sequence you run on every case",[
 "**1.** Identify the impairments",
 "**2.** Identify the needs of the task",
 "**3.** Identify the treatment bucket",
 "**4.** Pick a treatment",
 "**5.** Modify as needed — progress or regress"],C.gold,C.lightGold));

k.push(h1("2. Kelley — the Day 1 Eval"));
k.push(detail(["Measure","Finding"],[
 ["Knee ROM","Full, 0–135° bilaterally, pain-free"],
 ["Knee strength","4+/5 MMT"],
 ["Hip strength","4/5 MMT"],
 ["Pain at rest","0/10"],
 ["Pain with activity","3/10"],
 ["Lunge","Challenging — mild pain after repetition"],
 ["Squat","**Valgus collapse**"]],[3000,6360]));

k.push(h1("3. The Sync Cases"));
k.push(detail(["Case","Key findings","Treatment bucket"],[
 ["**Angela**, 16, high school swimmer. Bilateral shoulder pain during swim sessions, worse mid-season. Clicking and popping. Dislocated both shoulders years ago","Hypermobile in **all planes** · ROM hypermobile (**190° flexion**) · **Beighton +** · MMT 4+/5 ER, IR and parascapular · 0/10 at rest, **4/10 yesterday after 30 minutes of swimming when fatigued**","**Shoulder strengthening.** Rotator cuff — resisted IR and ER. Parascapular — **Y** (lower trap), **T** (middle trap), **I** (general)"],
 ["**Rob**, 55, right knee pain that comes on riding his bike 20–50 miles","Right knee −5° extension to 120° flexion vs left −1° to 130° · **hypomobile knee joint end feel** into flexion and extension · **hamstrings 90/90 positive on the right** · MMT 4+/5 quads, hamstrings, glutes · squat limited depth with mild valgus · 0/10 at rest, **5/10 with activity**","**Knee mobilization** into extension and flexion — the mobility deficit is the primary driver"],
 ["**Christina**, 26, runner. Knee pain from mile 8 training for Boston, none at rest","ROM normal · joint mobility normal · **hamstrings 90/90 negative · Ely's negative** · MMT 4+/5 glutes, hamstrings, quads","**Knee strengthening** — lunge patterns, squatting, single-leg deadlift"],
 ["**Lauren**, 36, fell on an outstretched arm skiing","AROM can't reach overhead · **PROM full** · resisted ER weak and painful · flexion 2+/5 · resisted IR normal","**Rotator cuff strengthening**"],
 ["**Sarah**, 23, college soccer player, 3 weeks post knee arthroscopy, fearful of 'ruining the surgery'","−10° extension to 95° flexion · **no end feel** · grimaces and asks you to stop · reports **no pain at all**, only fear","**Psychologically informed PT**"]],[2500,3900,2960]));
k.push(tip("Notice what separates Rob from Christina. Same joint, same sport-adjacent complaint, similar 4+/5 strength — but Rob has an asymmetric range deficit with a hypomobile end feel and a positive 90/90, and Christina has clean mobility with fatigue-onset pain. The exam findings, not the story, put them in different buckets."));

k.push(h1("4. Lab Techniques by Bucket"));
k.push(detail(["Bucket","Techniques"],[
 ["**Pain / fear**","Pain modulation — gentle ROM · rest · pain science education · **gentle grade 1 mobilizations**"],
 ["**Mobility — tissue extensibility**","**Hamstrings 90/90 positive → hamstring stretch.** **Ely's test positive → rectus femoris stretch**"],
 ["**Mobility — joint**","Mobilization or manipulation: knee joint · shoulder joint · ankle (talocrural) · lumbar PA glides · thoracic manipulation"],
 ["**Strength / stability**","Shoulder progression — rotator cuff, then periscapular. Knee progression — squat, then lunge. Ankle — anything closed chain"]],[2600,6760]));

k.push(...glossary("Quick-Reference Glossary — Sync Session 3",[
 ["Hamstrings 90/90 test","Hip flexed to 90°, knee passively extended from 90° to assess hamstring extensibility"],
 ["Ely's test","Prone knee flexion test for rectus femoris tightness"],
 ["Y / T / I exercises","Prone or inclined shoulder raises targeting lower trapezius (Y), middle trapezius (T) and general parascapular control (I)"],
 ["Grade 1 mobilization","Small-amplitude oscillation at the beginning of range, used for pain modulation rather than range gain"],
 ["PA glide","Posterior-to-anterior pressure applied to a vertebral segment"],
 ["Closed chain","Exercise performed with the distal segment fixed against a surface"]]));

k.push(linkBox("📚 Required reading for Module 3",[
 ["Neumann pg. 12",null,"— referenced on the Topic 3.1 mechanical properties slide"]],C.gold));

build(k,"/home/claude/out/Module3_TissueMechanicsNeedsAnalysis_StudyNotes.docx");
